"""
Word bank for THE EX-FILES.

THEMED  - the ex-girlfriend / breakup / guys-night vocabulary. These are the
          words the generator is told to prioritise, so every puzzle is
          loaded with theme.
FILL    - neutral crossword fill, there so the grids can actually be built
          without the author crying into a keyboard.

Clues are written for the book's voice: a 30-something man, three beers in,
being extremely brave about all of it.
"""

# ---------------------------------------------------------------------------
# THEMED
# ---------------------------------------------------------------------------
THEMED = {
    # ---- 3 letters ----
    "EX": "The one whose name you now say like a curse",
    "BAR": "Where you go to forget, or to remember very loudly",
    "SEX": "Allegedly a thing people are still having",
    "GYM": "January's most popular address",
    "ALE": "Liquid coping, served in a pint",
    "NAG": "What she called it; what you called talking",
    "HUG": "Physical contact from a guy friend, two pats maximum",
    "DOG": "She got custody. Obviously.",
    "KEG": "Party equipment for a man who is 22 at heart",
    "BAE": "Word you weren't allowed to say even ironically",
    "SIN": "What the group chat says you're guilty of",
    "HIM": "The guy you were told not to worry about",
    "BUM": "What you became on the couch for six weeks",
    "IOU": "Paper evidence of the forty bucks you borrowed",
    "SUE": "What you swore you'd do, and absolutely won't",
    "WOE": "Your general vibe, per the algorithm",
    "FLU": "The excuse for skipping her cousin's wedding",
    "PIT": "What your stomach does when her name appears",
    "GAS": "What you claim to smell so you can leave early",
    "CAB": "Your ride home at two a.m., alone, with the radio off",
    "BRO": "Term of endearment, or a warning",
    "MOB": "Her family, as described to the guys",
    "AGE": "What you shaved three years off of online",
    "AIM": "What you had, then lost, then found at the gym",
    "BEE": "What is in your bonnet about her new guy",
    "OAF": "What her father clearly thought you were",
    "RAT": "What you called him. He's probably fine.",
    "SEA": "Where the plenty of other fish allegedly live",
    "TIP": "Unrequested advice from the group chat",
    "TAB": "What you left open at the bar, and also in life",
    "GAP": "What she said the two of you needed",
    "SAP": "What your brother calls you now",
    "ABS": "What you loudly promised to get",
    "ART": "What she said you never appreciated",
    "BET": "What the guys placed on how long you'd last",
    "JAB": "A cheap shot at her new man, online, at 1 a.m.",
    "MUG": "What you made of yourself on her Instagram",
    "ICE": "What you put on your knuckles after the wall thing",
    "NAP": "What you do now at four in the afternoon",
    "ODD": "What the numbers look like, per her mother",
    "OWE": "What you still do, per the IOU",
    "PUP": "What you want to adopt so you can feel again",
    "RUG": "What got yanked",
    "SIR": "What she called you once it was over",
    "DUO": "What you are no longer half of",
    "EGO": "What her therapist said got bruised",
    "FEE": "What the lawyer wants, up front",
    "GUY": "The other one",
    "HIS": "Pronoun you now use for the dog",
    "ILL": "What you claim to be, to skip brunch",
    "JOB": "Thing she said you might want to get",
    "KID": "What you insist you still are, at 34",
    "MAD": "What you tell everyone you are not",
    "ODE": "What you wrote at 2 a.m. and deleted at 2:04",
    "OWL": "What you are at three in the morning",
    "PAN": "What her mother thought you were",
    "PRO": "What the group chat believes itself to be",
    "ROW": "What the fight technically was",
    "SKY": "The limit, allegedly",
    "SOB": "What you do in the car in the parking garage",
    "TEA": "What the group chat truly wants",
    "TIE": "The one thing of yours the dog still has",
    "WAR": "What it became",
    "YAK": "What you do about it to anyone who'll listen",
    "ZIT": "What stress did to your forehead",
    "FIT": "What you threw. Also what you're getting.",
    "GUT": "Where you feel it, and what you should trust",
    "PIG": "What the group chat calls you when you text her",
    "TAX": "What's due, and what she said you were",
    "CEL": "What she called you when she was done with you",
    "COP": "What you got called for the noise complaint",
    "SPA": "Where she went the day after and you didn't",
    "GEL": "What you can't do your hair with because you're out",
    "FLY": "What you think you look like now",
    "PAD": "What you're on now, alone, at her mom's house",
    "HER": "Possessive you can't say anymore without an eye roll",
    "LAW": "What your cousin says you should look into",
    "LIP": "What you have yet to give her, hopefully",
    "SIX": "How many times you re-read the text",
    "PUB": "Where the group chat convenes to fix you",
    "RED": "What the flag was, per your sister",
    "SAD": "State of the union, and of your playlist",
    "SHY": "What you became around her friends",
    "SPY": "What the app makes you feel like",
    "YAP": "What you do about her to strangers at the bar",
    "ZOO": "What her family reunion resembled",
    "INK": "What your new tattoo is made of. Regret is later.",
    "IVY": "What she said grew on you. She meant it badly.",
    "JAM": "What you were in, financially and emotionally",
    "LOT": "Where you now park and stare at the windshield",
    "OFF": "What you are. Entirely.",
    "OIL": "What she said would fix your car, and your attitude",
    "OPT": "What you do out of every group event",
    "OWN": "What you have to, eventually",
    "PAW": "What her dog put on your lap. You cried.",
    "PEG": "What she said you were to her mother",
    "PLY": "What you do her friends with, awkwardly",
    "RAW": "Where you are emotionally, and how you eat sushi",
    "RUN": "What you claim the gym was for",
    "SEW": "What she offered to teach you, twice",
    "SLY": "What the group chat thinks you are for talking to her cousin",

    # ---- 4 letters ----
    "BEER": "The fifth food group",
    "EXES": "People you now search for at 1 a.m.",
    "BROS": "The guys, formally",
    "DUDE": "What the carpet is now called in your apartment",
    "TEXT": "Three dots that ruined your Tuesday",
    "WINE": "What both mothers somehow blamed",
    "MOPE": "To sit shirtless in a dark room with a podcast on",
    "SOBS": "Crying, but with visible chest movement",
    "WING": "What you are to a buddy, and also what you eat",
    "GRUB": "What you eat at 2 a.m. instead of feelings",
    "LADS": "The lads",
    "JILT": "To get left at the altar",
    "FLAT": "What her poet boyfriend's voice sounds like",
    "MALE": "What she now says your problems are",
    "NUDE": "What you sent. Bold. Unwise.",
    "MATE": "What her dog now calls somebody else",
    "DIVE": "The bar you now frequent religiously",
    "BUZZ": "What exactly two IPAs produce",
    "CUFF": "The season you were in briefly",
    "SWIG": "A pull from the bottle at a children's party",
    "SORE": "How you are about her story, and your back",
    "GLOW": "What she did afterwards, publicly",
    "MOOD": "What the group chat says you're in",
    "LOSS": "What it is, and what you are",
    "KNEE": "Where you land when the dog picks her",
    "PITY": "What you don't want and will take anyway",
    "MESS": "What the kitchen is, and mildly what you are",
    "ROOM": "The one she moved out of, leaving the smell",
    "SIGH": "Your primary form of communication now",
    "HUNG": "How you insist the painting was",
    "ISLE": "What you walk down at everyone else's wedding",
    "VOWS": "Promises you 85 percent kept",
    "ITCH": "Where every new relationship starts",
    "SOFA": "Where you sleep now, by choice, spiritually",
    "PALE": "How the mirror reports you",
    "SWAP": "What happens to your stuff during a breakup",
    "EYED": "What the bartender did on your third order",
    "HURT": "What you insist you are not",
    "BALD": "Your 35th birthday gift to yourself",
    "LATE": "How she was for everything except the breakup",
    "DUMB": "Your assessment of yourself at 3 a.m.",
    "BLOB": "What you became on the couch",
    "TACO": "The best thing about Tuesday now",
    "PINT": "The officially recognised unit of healing",
    "MOAN": "The noise you made opening the vet bill",
    "CLUB": "Place you didn't get into, twice, wearing a hat",
    "DARE": "What the group chat double-dogged you into",
    "RAIN": "What came to your parade specifically",
    "LUMP": "What you found where your heart used to be",
    "DORK": "What she called you lovingly, then not so much",
    "SPAT": "The small fight that became the big one",
    "HISS": "What her roommate did when you walked in",
    "BARK": "What her dog does at your car, sadly, loyally",
    "FLEE": "What you should do when the invite arrives",
    "GONE": "Her status. Also your record collection.",
    "DONE": "What you loudly claim to be",
    "BOOB": "What you were, and also a body part",
    "BATH": "What you now take at nine p.m. by candlelight",
    "CHUG": "How you drink a beverage now",
    "DAMP": "The condition of your pillow, mildly",
    "FLAB": "What six weeks of couch delivered",
    "NUMB": "Your reported feeling level, for the record",
    "HERO": "What the bartender called you at closing",
    "ZERO": "What you feel like, and your odds, per her",
    "WOLF": "What you claim to do at her friend's brunch",
    "CORN": "What the group chat says her new man is full of",
    "MILD": "The salsa you now order, out of respect for your gut",
    "CRAB": "What you become at other people's happiness",
    "TRIM": "What you swear you're getting back into",
    "YOGA": "What she said would help. You did one class.",
    "BATH": "What you take at nine p.m. with a podcast on",
    "GOLF": "Where the guys take you to have feelings about it",
    "EARN": "What you now have to do for her half of the couch",
    "ACHE": "What the songs do, in your throat",
    "WEAK": "How you got when her mom called",
    "MAID": "Who she said did everything, before she left",
    "SLID": "What you did into her DMs and then into shame",
    "FIAT": "The car you sold to afford the ring",
    "GUSH": "What her mother does about the new one",
    "MEAL": "What you cook now: eggs, at 10 p.m.",
    "ROSE": "What you sent to apologize. Wrong address.",
    "SNAP": "What you did, finally, at her brother's wedding",

    # ---- 5 letters ----
    "BREAK": "The noun you keep saying you need",
    "SWIPE": "Motion you allegedly made near her sister",
    "BOOZE": "Coping, but make it social",
    "WINGS": "The non-negotiable food group of guys' night",
    "BROKE": "Your state, financially then emotionally",
    "GUYS": "The panel you lied to, to their faces",
    "PIZZA": "The real rebound",
    "TEXTS": "Drafts you wrote, polished, and never sent",
    "NIGHT": "What you now have plenty of, alone",
    "SPLIT": "What happened, and what the check should be",
    "THIRD": "What you are now, to her, permanently",
    "ALONE": "State of the union, and of the fridge",
    "DRUNK": "How you explained it to her mother",
    "TEARS": "What you claim were seasonal allergies",
    "MOVED": "What she did without telling you first",
    "SOBER": "What you'll be on Monday. Probably.",
    "HAPPY": "What you tell your mom you are, at speed",
    "SWEAT": "What the gym is actually for, emotionally",
    "BEARD": "What your ex said you were to your best friend",
    "BLOKE": "Lads, but with a British accent",
    "DRAMA": "What she told everyone the whole thing was",
    "PIECE": "What you say you lost. The other one.",
    "LONER": "Self-description with a rotating hobby attached",
    "TRUST": "What left the building and took the dog",
    "MONEY": "What she swore it was never about",
    "CHEAP": "How your date described your date",
    "STAGE": "What your sister says you're going through",
    "SPACE": "What she asked for, then took entirely",
    "SPITE": "Your primary gym motivation",
    "SALTY": "Your vibe after the engagement post",
    "SCRAP": "What the group chat turned into over the venue",
    "VENTS": "What you do at your roommate for 40 minutes",
    "ADULT": "What you are pretending to be in front of a mortgage",
    "COUCH": "Where you sleep, rule out furniture-based growth",
    "ORDER": "The thing she said you had to get, and you didn't",
    "CRIES": "What the shower is for, quietly",
    "HEART": "What she broke, allegedly, per your bio",
    "SHAVE": "What you stopped doing for eleven days",
    "LOOSE": "How the group chat describes her morals, unfairly",
    "WOUND": "What it left, and what you keep poking",
    "GRIND": "The mode you claim to be in now",
    "REPLY": "What you're waiting for, like a house cat",
    "BLOCK": "What you did at 2 a.m. and undid at 2:09",
    "RUMOR": "What the block party heard about you",
    "STUFF": "What is currently being divided in a driveway",
    "BINGE": "What you did with the show you watched together",
    "PHONE": "Object you are staring at right now, at 1 a.m.",
    "STALK": "What the app calls checking her story, actually",
    "PUNCH": "What you didn't do, per your lawyer's letter",
    "SORRY": "The word you used four hundred times, uselessly",
    "BLAME": "What nobody in the thread will accept",
    "FREED": "What you claim to be, in all caps",
    "STRAY": "What you are now, per your mother",
    "FLING": "What the group chat insists you need immediately",
    "DOGGO": "Her dog, renamed by you, in secret, forever",
    "RUGBY": "Where you watch large men solve problems legally",
    "BEERS": "What you order for two when you forget",
    "GROWN": "What you claim to be when the check arrives",
    "LOSER": "What the mirror says, and also the game on Sunday",
    "MONEY": "What she swore it was never about",
    "NACRE": "Fancy shell stuff you couldn't afford for her",
    "OCEAN": "The size of the fish population you're told about",
    "PEACE": "What you're told you'll find. Terms unclear.",
    "QUILT": "What you sleep under alone, at noon, on a Tuesday",
    "SMILE": "What you perform for the family photos",
    "HINGE": "Door part she said you should have been",
    "DATED": "What the milk, and you, are",
    "FADED": "What her last text to you did over three weeks",
    "SPENT": "What you are, and what the joint account is",
    "TRASH": "What her friends think of your haircut",
    "VODKA": "What got you through her work Christmas party",
    "WHINE": "What you do about the whole thing, occasionally",
    "TOXIC": "Word the internet taught her for you",
    "OUNCE": "What's left of your dignity, measured",
    "BELCH": "What you can now do at the table, freely, sadly",

    # ---- 6 letters ----
    "SINGLE": "Relationship status: complicated but actually no",
    "UNSENT": "The bravest texts you ever composed",
    "CRYING": "What the shower is for, and the parking garage",
    "GROVEL": "What you did on the doorstep on a Tuesday",
    "BROKEN": "The state of the item, and also you",
    "TISSUE": "Item you now buy in the industrial box",
    "SHOWER": "Where you do your best thinking and worst crying",
    "FRIEND": "What you bravely offered to be. Bold. Unwise.",
    "STUPID": "The adjective in every draft in your notes app",
    "MOVING": "What you said you'd be doing 'soon' for nine months",
    "SORROW": "Emotion with a country song and a beer named after it",
    "WALLOW": "What you do in self-pity, shirtless, with snacks",
    "SPIRAL": "What two a.m. does to your thoughts, fast",
    "BUZZED": "Two drinks in, emotionally available, dangerous",
    "BAILED": "What you did on the third date, mid-appetizer",
    "SEXTED": "Risky behaviour, especially at 38",
    "VIBING": "What you claim you're doing, alone, in a car",
    "DUMPED": "Your status, legally and socially",
    "JILTED": "Left at the altar, formally",
    "SWIPED": "What you did on the app while in a queue",
    "SECRET": "What you told the group chat not to tell anyone",
    "REGRET": "What the tattoo is going to be about",
    "DENIAL": "The first stage, per a podcast you half-heard",
    "CLINGY": "What her friends called you. Rude. Accurate.",
    "BROODY": "What you became at other people's brunches",
    "MOPING": "What the couch is specially designed for",
    "MANTRA": "What the wellness podcast told you to repeat",
    "EXCUSE": "What 'I'm fine' is, structurally",

    # ---- 7 letters ----
    "CLOSURE": "What you can't get from an app, apparently",
    "DIVORCE": "The lawyers' favourite growth industry",
    "WHISKEY": "Coping, but with a label and a story",
    "THERAPY": "Paying a stranger to hear the same story weekly",
    "MISSING": "What her dog is doing to you, constantly",
    "SUNDAYS": "The day that now feels openly hostile",
    "BLOCKED": "What you are, and what the group chat did to you",
    "GALLERY": "What you cannot look at, and looked at",
    "GHOSTED": "Left on read, permanently, by a coward",
    "SOBBING": "What the neighbour reported at 1 a.m.",
    "DIALING": "The action you stopped 90 percent of the way through",
    "TEXTING": "The activity your thumbs regret",
    "SEXTING": "What the guy in the group chat won't stop doing",
    "REBOUND": "A person who deserves better, honestly",
    "WEEPING": "Crying, but with production value",
    "BLUBBER": "To cry openly, per your brother's review",
    "FREEDOM": "What you claim to have, through gritted teeth",
    "DRINKER": "Your self-description in any online form",
    "WISTFUL": "What your face looks like at other people's weddings",
    "ALIMONY": "The word the lawyer brought up unsettlingly fast",
    "DIGNITY": "What you left in the group chat in March",

    # ---- 8 letters ----
    "PLAYLIST": "What you should stop listening to, immediately",
    "HANGOVER": "What Sunday delivers, generously",
    "BLOCKING": "The method by which you achieved peace, briefly",
    "GHOSTING": "Cowardice with a good Wi-Fi connection",
    "REJECTED": "What the venue, the ring, and you all are",
    "SPIRALED": "What you did at 3 a.m. with a phone in your hand",
    "DIVORCED": "Legally undone, with a fee attached",
    "SETTLING": "What you swore you would never be caught doing",
    "MISTAKEN": "How you now describe the entire last year",
    "RECOVERY": "The mode you claim to be in, loudly, at brunch",
}


# ---------------------------------------------------------------------------
# FILL  (neutral crossword filler)
# ---------------------------------------------------------------------------
FILL = {
    # ---- 3 letters ----
    "ARE": "First word of many useless apologies",
    "ORE": "Rock with metal in it",
    "ODE": "Poem of praise",
    "ERA": "Long stretch of time",
    "ION": "Charged particle",
    "ELM": "Tree on Elm Street",
    "APE": "Big primate",
    "OAR": "Rowboat paddle",
    "OWL": "Night hooter",
    "EAR": "Corn unit",
    "ARM": "Limb",
    "TEA": "Afternoon drink",
    "TIE": "Necktie",
    "POD": "Peas come in one",
    "TON": "Two thousand pounds",
    "NIL": "Nothing at all",
    "EVE": "Night before",
    "ACE": "Card above king",
    "OAK": "Sturdy wood",
    "JAR": "Pickle container",
    "KIT": "Set of parts",
    "LID": "Pot topper",
    "LOG": "Timber",
    "MAP": "Atlas page",
    "MAT": "Welcome ___",
    "MUD": "Wet earth",
    "NET": "What a goalie guards",
    "NOD": "Head bob",
    "NUT": "Cashew or pecan",
    "PAD": "Notebook",
    "PAN": "Skillet",
    "PEA": "Pod vegetable",
    "PEN": "Ink pen",
    "PET": "Beloved animal",
    "PIE": "Dessert with a crust",
    "PIN": "Bowling target",
    "POT": "Cooking vessel",
    "RAG": "Cleaning cloth",
    "RAM": "Male sheep",
    "RAY": "Sunbeam",
    "RIB": "Chest bone",
    "RIM": "Edge of a cup",
    "RIP": "Tear, or a tombstone word",
    "ROB": "Steal from",
    "ROD": "Fishing pole",
    "ROT": "Decay",
    "ROW": "Line of seats",
    "RUB": "Massage",
    "SET": "Put down",
    "SIP": "Small drink",
    "SIX": "Half a dozen",
    "SKI": "Slalom gear",
    "SKY": "Above the clouds",
    "SON": "Male offspring",
    "SPA": "Hot tub place",
    "SPY": "Secret agent",
    "SUM": "Total",
    "SUN": "Daytime star",
    "TAG": "Price label",
    "TAN": "Beach shade",
    "TAP": "Faucet",
    "TAR": "Road goo",
    "TAX": "What April takes",
    "TIN": "Metal can",
    "TOE": "Foot digit",
    "TOP": "Spinning toy",
    "TOW": "Haul behind",
    "TOY": "Plaything",
    "TUB": "Bath container",
    "VET": "Animal doctor",
    "VOW": "Pledge",
    "WAG": "Tail motion",
    "WEB": "Spider's work",
    "WIG": "Hairpiece",
    "ZIP": "Fastener",
    "ASH": "Fire leftover",
    "APT": "Suiting the moment",
    "BAY": "Body of water",
    "BED": "Place for sleep",
    "BOA": "Constrictor snake",
    "BOX": "Cardboard container",
    "BUD": "Pals, or a flower start",
    "BUG": "Insect",
    "CAP": "Hat",
    "CAR": "Road vehicle",
    "CAT": "Feline",
    "COW": "Milk source",
    "CUB": "Baby bear",
    "DAM": "Beaver's build",
    "DEN": "Cozy room",
    "DEW": "Morning moisture",
    "DIM": "Not bright",
    "DIP": "Salsa move",
    "DOT": "Polka mark",
    "DRY": "Not wet",
    "DYE": "Colour fabric",
    "EEL": "Slippery fish",
    "EGG": "Nest item",
    "ELK": "Big antlered beast",
    "END": "Finish",
    "FAN": "Admirer or breezer",
    "FAR": "A long way off",
    "FIG": "Fruit in a Newton",
    "FIN": "Shark's edge",
    "FIR": "Evergreen",
    "FLY": "House pest",
    "FOX": "Sly animal",
    "FUN": "Good time",
    "FUR": "Coat material",
    "GEM": "Precious stone",
    "GIN": "Juniper spirit",
    "GUM": "Chewing stuff",
    "GUN": "Holster filler",
    "GUT": "Belly",
    "HAY": "Barn bundle",
    "HEN": "Female chicken",
    "HOP": "Bunny jump",
    "HUE": "Shade of colour",
    "HUT": "Small shack",
    "INK": "Pen filler",
    "INN": "Roadside lodging",
    "IVY": "Wall climber",
    "JAW": "Chewing joint",
    "JET": "Fast plane",
    "JOY": "Delight",
    "KEY": "Lock opener",
    "KIN": "Relatives",
    "LAB": "Science room",
    "LAW": "Statute",
    "LEG": "Table support",
    "LIP": "Rim of a cup",
    "LOT": "Parking area",
    "LOW": "Not high",
    "MOP": "Floor cleaner",
    "NAP": "Short sleep",
    "OIL": "Frying stuff",
    "OPT": "Choose",
    "ORB": "Sphere",
    "OUT": "Not in",
    "OWN": "Possess",
    "PAW": "Animal foot",
    "PEG": "Board hole plug",
    "PLY": "Work with, as a trade",
    "PRO": "Expert, for short",
    "PUB": "British bar",
    "RAW": "Uncooked",
    "RED": "Stop-sign colour",
    "RUN": "Jog",
    "RYE": "Deli bread",
    "SAD": "Unhappy",
    "SEW": "Stitch",
    "SHY": "Bashful",
    "SIT": "Take a seat",
    "SLY": "Cunning",
    "SOD": "Turf",
    "SOW": "Plant seeds",
    "SOY": "Tofu bean",
    "TEN": "Half a score",
    "TOE": "Foot part",
    "TUG": "Sharp pull",
    "TUX": "Formal suit, briefly",
    "URN": "Coffee server",
    "VAN": "Moving vehicle",
    "VAT": "Big tub",
    "VIA": "By way of",
    "VIE": "Compete",
    "WAX": "Candle stuff",
    "WAY": "Route",
    "WED": "Marry",
    "WIN": "Take first",
    "WIT": "Sharp humour",
    "WOK": "Stir-fry pan",
    "YAM": "Sweet potato",
    "YAP": "Chatter",
    "YEW": "Evergreen with red berries",
    "ZAP": "Taser sound",
    "ZEN": "Calm state",
    "ZOO": "Animal park",

    # ---- 4 letters ----
    "ALSO": "Additionally",
    "ANTE": "Poker stake",
    "AREA": "Region",
    "ARIA": "Opera solo",
    "ATOM": "Tiny particle",
    "AXLE": "Wheel rod",
    "BARN": "Farm building",
    "BEEF": "Meat, or a grudge",
    "BOLT": "Nuts companion",
    "CAFE": "Coffee spot",
    "CANE": "Walking stick",
    "CHIN": "Jaw front",
    "CLAM": "Shellfish",
    "COAT": "Winter layer",
    "CODE": "Secret writing",
    "COIN": "Pocket change",
    "COMB": "Hair tool",
    "CORN": "Cob crop",
    "CROW": "Black bird",
    "DART": "Pub game missile",
    "DEAL": "Agreement",
    "DEER": "Forest grazer",
    "DOLL": "Toy figure",
    "DOOR": "Doorway panel",
    "DRUM": "Kit item",
    "DUCK": "Pond bird",
    "DUNE": "Sand hill",
    "DUST": "Shelf film",
    "EACH": "Every one",
    "EARN": "Deserve",
    "EASE": "Comfort",
    "ECHO": "Sound that comes back",
    "EDGE": "Border",
    "ELSE": "Otherwise",
    "EPIC": "Grand in scale",
    "EVEN": "Flat and level",
    "EXAM": "Big test",
    "FACE": "Front of a head",
    "FACT": "True statement",
    "FAIR": "Just, or a midway",
    "FARM": "Where crops grow",
    "FERN": "Frond plant",
    "FILE": "Folder item",
    "FILM": "Movie",
    "FISH": "Angler's target",
    "FLAG": "Pole banner",
    "FOAM": "Soap bubbles",
    "FOLD": "Crease",
    "FORK": "Utensil with tines",
    "GAIT": "Way of walking",
    "GATE": "Fence opening",
    "GIFT": "Present",
    "GLUE": "Sticky stuff",
    "GOAT": "Horned climber",
    "GOLD": "Medal metal",
    "GOLF": "Sport with clubs",
    "GRID": "Crossword frame",
    "HALO": "Angel ring",
    "HARP": "Stringed angel instrument",
    "HAWK": "Hunting bird",
    "HEAL": "Get better",
    "HEAT": "Summer warmth",
    "HERB": "Kitchen plant",
    "HILL": "Mound",
    "HIVE": "Bee home",
    "HORN": "Brass instrument",
    "HOST": "Party thrower",
    "HOUR": "Sixty minutes",
    "IDEA": "Thought",
    "IDOL": "Worshipped figure",
    "INCH": "Ruler unit",
    "IRIS": "Eye part",
    "ITEM": "List entry",
    "JADE": "Green stone",
    "KELP": "Seaweed",
    "KITE": "Wind toy",
    "KNOT": "Rope tangle",
    "LACE": "Shoe tie",
    "LAMP": "Light source",
    "LANE": "Bowling path",
    "LARK": "Songbird",
    "LAVA": "Volcano flow",
    "LAWN": "Grass patch",
    "LEAF": "Tree part",
    "LENS": "Camera glass",
    "LIME": "Green citrus",
    "LIMB": "Arm or leg",
    "LION": "Big cat",
    "LOAF": "Bread block",
    "LOOP": "Coil",
    "LORE": "Folk knowledge",
    "LUCK": "Chance",
    "LUNG": "Breathing organ",
    "MANE": "Horse hair",
    "MASK": "Face cover",
    "MAZE": "Puzzle of paths",
    "MILE": "Distance unit",
    "MILK": "Dairy drink",
    "MOAT": "Castle ditch",
    "MOLD": "Shape, or a fuzzy growth",
    "MOON": "Night light",
    "MOSS": "Green fuzz",
    "MOTH": "Lamp botherer",
    "MULE": "Stubborn hybrid",
    "MUST": "Have to",
    "NEST": "Bird home",
    "NEWS": "Evening report",
    "NOTE": "Sticky message",
    "OATH": "Solemn promise",
    "ONCE": "One single time",
    "OPEN": "Not shut",
    "OVAL": "Egg-shaped",
    "OVEN": "Baking box",
    "PACE": "Walking speed",
    "PAGE": "Book unit",
    "PAIL": "Bucket",
    "PALM": "Hand part",
    "PARK": "Green space",
    "PATH": "Trail",
    "PAVE": "Surface a road",
    "PEAK": "Summit",
    "PEAR": "Green fruit",
    "PIER": "Dock",
    "PINE": "Evergreen",
    "PLAN": "Scheme",
    "PLOT": "Story line",
    "PLUM": "Purple fruit",
    "POEM": "Verse",
    "POND": "Small lake",
    "POOL": "Swim spot",
    "PORE": "Skin opening",
    "PORT": "Harbour",
    "PRAY": "Say a prayer",
    "PUMP": "Gas dispenser",
    "QUIZ": "Short test",
    "RAFT": "Floating platform",
    "RAIL": "Fence bar",
    "RAIN": "Falling water",
    "RAMP": "Incline",
    "RANK": "Position, or smelly",
    "REED": "Marsh grass",
    "RELY": "Depend",
    "RENT": "Monthly payment",
    "RICE": "Grain side",
    "RING": "Phone sound, or a circle",
    "RISE": "Go up",
    "RISK": "Gamble",
    "ROAD": "Street",
    "ROAR": "Lion's sound",
    "ROBE": "Bath wrap",
    "ROCK": "Stone",
    "ROLE": "Part to play",
    "ROOF": "House top",
    "ROPE": "Thick cord",
    "ROSE": "Thorny flower",
    "RULE": "Regulation",
    "RUST": "Iron damage",
    "SAIL": "Boat canvas",
    "SALT": "Shaker filler",
    "SAND": "Beach grain",
    "SEAL": "Ocean mammal",
    "SEAT": "Chair",
    "SHIP": "Big vessel",
    "SHOE": "Footwear",
    "SHOP": "Store",
    "SILK": "Soft fabric",
    "SING": "Use your voice",
    "SITE": "Location",
    "SLED": "Snow rider",
    "SLOT": "Coin opening",
    "SNAP": "Photo, or a sound",
    "SNOW": "Winter fall",
    "SOAP": "Bar in the shower",
    "SOCK": "Foot cover",
    "SOIL": "Dirt",
    "SONG": "Tune",
    "SOUP": "Bowl of broth",
    "SPIN": "Turn around",
    "SPOT": "Mark",
    "STAR": "Night twinkler",
    "STAY": "Remain",
    "STEM": "Plant stalk",
    "STEP": "Stair unit",
    "STEW": "Slow-cooked dish",
    "SWAN": "Graceful bird",
    "SWIM": "Pool activity",
    "TALE": "Story",
    "TALK": "Speak",
    "TAME": "Not wild",
    "TAPE": "Sticky strip",
    "TASK": "Job",
    "TEAM": "Squad",
    "TENT": "Camper's shelter",
    "TIDE": "Ocean rise",
    "TIDY": "Neat",
    "TIER": "Row of seats",
    "TILE": "Floor square",
    "TIME": "Clock reading",
    "TOAD": "Warty hopper",
    "TOLL": "Road charge",
    "TONE": "Pitch",
    "TOWN": "Small city",
    "TREE": "Maple or oak",
    "TRIM": "Cut back",
    "TROT": "Brisk gait",
    "TUNE": "Melody",
    "TURN": "Rotate",
    "TWIG": "Small branch",
    "VASE": "Flower holder",
    "VAST": "Huge",
    "VEIL": "Bridal cover",
    "VEIN": "Blood vessel",
    "VERB": "Action word",
    "VEST": "Sleeveless layer",
    "VIEW": "Scenery",
    "VINE": "Climbing plant",
    "WALK": "Stroll",
    "WALL": "Room divider",
    "WAND": "Magician's stick",
    "WAVE": "Ocean curl",
    "WELL": "Water source",
    "WEST": "Sunset direction",
    "WIDE": "Broad",
    "WILD": "Untamed",
    "WIND": "Breeze",
    "WIRE": "Metal strand",
    "WOLF": "Pack hunter",
    "WOOD": "Timber",
    "WOOL": "Sheep coat",
    "WORD": "Dictionary entry",
    "WORK": "Job",
    "YARD": "Front lawn",
    "YARN": "Knitting fibre",
    "YEAR": "Twelve months",
    "ZEAL": "Enthusiasm",
    "ZONE": "Area",

    # ---- 5 letters ----
    "ADOBE": "Brick of clay",
    "ALBUM": "Photo book",
    "ALERT": "Watchful",
    "ALIVE": "Not dead",
    "ALLOY": "Metal blend",
    "ANGEL": "Winged being",
    "ANKLE": "Leg joint",
    "APPLE": "Pie fruit",
    "ARENA": "Big venue",
    "ARGUE": "Bicker",
    "AROMA": "Pleasant smell",
    "ASIDE": "Stage whisper",
    "ATLAS": "Map book",
    "AWAKE": "Not asleep",
    "BACON": "Breakfast strip",
    "BADGE": "Security pass",
    "BAKER": "Bread maker",
    "BATON": "Relay stick",
    "BEACH": "Sandy shore",
    "BEAST": "Wild animal",
    "BEGAN": "Got started",
    "BELLY": "Tummy",
    "BENCH": "Park seat",
    "BERRY": "Small fruit",
    "BIRCH": "White-bark tree",
    "BISON": "Shaggy plains beast",
    "BLADE": "Knife edge",
    "BLAME": "Point a finger",
    "BLANK": "Empty",
    "BLAST": "Explosion",
    "BLAZE": "Big fire",
    "BLEND": "Mix together",
    "BLIMP": "Floating balloon",
    "BLINK": "Shut both eyes",
    "BLOCK": "Cube",
    "BLOOM": "Flower opening",
    "BOARD": "Plank",
    "BONUS": "Extra reward",
    "BOOTH": "Phone cubicle",
    "BRAID": "Interwoven hair",
    "BRAIN": "Thinking organ",
    "BRAKE": "Slow the car",
    "BRAND": "Logo name",
    "BRASS": "Horn metal",
    "BREAD": "Loaf",
    "BRICK": "Wall block",
    "BRIDE": "One in white",
    "BRIEF": "Short",
    "BROOK": "Small stream",
    "BROOM": "Sweeper",
    "BRUSH": "Paint tool",
    "BUNCH": "Cluster",
    "BUNNY": "Long-eared hopper",
    "CABIN": "Wooden hut",
    "CABLE": "TV cord",
    "CAMEL": "Humped desert ride",
    "CANAL": "Man-made waterway",
    "CANDY": "Sweet treat",
    "CANOE": "Paddled boat",
    "CARGO": "Ship's freight",
    "CAROL": "Yule song",
    "CARRY": "Tote",
    "CATCH": "Grab",
    "CAUSE": "Reason",
    "CEDAR": "Aromatic wood",
    "CHAIN": "Linked metal",
    "CHAIR": "Seat",
    "CHALK": "Blackboard stick",
    "CHARM": "Bracelet trinket",
    "CHART": "Graph",
    "CHASE": "Pursue",
    "CHECK": "Verify",
    "CHEER": "Shout support",
    "CHESS": "Board game with kings",
    "CHEST": "Treasure box",
    "CHIEF": "Leader",
    "CHILD": "Youngster",
    "CHILL": "Cool down",
    "CHIME": "Bell ring",
    "CHINA": "Fine dishes",
    "CHIRP": "Bird sound",
    "CHOIR": "Singing group",
    "CHORE": "Household task",
    "CIDER": "Apple drink",
    "CIVIC": "Of a city",
    "CLAIM": "Assert",
    "CLAMP": "Grip tight",
    "CLASH": "Conflict",
    "CLASS": "Lesson group",
    "CLEAN": "Not dirty",
    "CLEAR": "Transparent",
    "CLERK": "Store worker",
    "CLICK": "Mouse press",
    "CLIFF": "Steep rock face",
    "CLIMB": "Go up",
    "CLOCK": "Wall timer",
    "CLOSE": "Shut",
    "CLOTH": "Fabric",
    "CLOUD": "Sky puff",
    "CLOVE": "Spice bud",
    "COACH": "Team boss",
    "COAST": "Shoreline",
    "COBRA": "Hooded snake",
    "COCOA": "Hot chocolate base",
    "COLON": "Punctuation mark",
    "COLOR": "Hue",
    "COMET": "Tailed sky rock",
    "COMIC": "Funny person",
    "CORAL": "Reef builder",
    "COUNT": "Add up",
    "COURT": "Tennis surface",
    "COVER": "Put over",
    "CRAFT": "Skilled trade",
    "CRANE": "Lifting machine",
    "CRASH": "Collide",
    "CRAWL": "Move on all fours",
    "CREAM": "Coffee lightener",
    "CREEK": "Small stream",
    "CREST": "Top of a hill",
    "CRIME": "Illegal act",
    "CROWD": "Big group",
    "CROWN": "Royal headpiece",
    "CRUMB": "Bread bit",
    "CRUST": "Pie edge",
    "CURVE": "Bend",
    "CYCLE": "Bike, or a loop",
    "DAILY": "Every day",
    "DAIRY": "Milk section",
    "DAISY": "Simple white flower",
    "DANCE": "Move to music",
    "DEBUT": "First appearance",
    "DECAY": "Rot away",
    "DECOY": "Lure",
    "DELAY": "Hold up",
    "DELTA": "River mouth",
    "DENSE": "Thick",
    "DEPOT": "Storage station",
    "DEPTH": "Deepness",
    "DERBY": "Hat, or a horse race",
    "DIARY": "Journal",
    "DIGIT": "Number, or a finger",
    "DINER": "Roadside eatery",
    "DIRTY": "Grubby",
    "DISCO": "Dance floor era",
    "DITCH": "Abandon",
    "DIVER": "Pool plunger",
    "DIZZY": "Lightheaded",
    "DODGE": "Avoid",
    "DONOR": "Giver",
    "DONUT": "Ring pastry",
    "DOZEN": "Twelve",
    "DRAIN": "Sink hole",
    "DREAM": "Sleep vision",
    "DRESS": "Frock",
    "DRIFT": "Float along",
    "DRILL": "Bore a hole",
    "DRINK": "Beverage",
    "DRIVE": "Steer a car",
    "DRONE": "Buzzing flyer",
    "DROVE": "Past tense of drive",
    "DWELL": "Linger",
    "EAGLE": "Soaring raptor",
    "EARLY": "Before time",
    "EARTH": "Third planet",
    "EBONY": "Black wood",
    "EIGHT": "Two fours",
    "ELBOW": "Arm joint",
    "ELDER": "Older one",
    "ELECT": "Vote in",
    "ELITE": "Top tier",
    "EMAIL": "Inbox item",
    "EMBER": "Glowing coal",
    "EMPTY": "Containing nothing",
    "ENEMY": "Foe",
    "ENJOY": "Like a lot",
    "ENTER": "Go in",
    "ENTRY": "Way in",
    "EQUAL": "The same",
    "ERASE": "Rub out",
    "ERROR": "Mistake",
    "ESSAY": "Written piece",
    "EVENT": "Occasion",
    "EXACT": "Precise",
    "EXILE": "Forced outcast",
    "EXTRA": "Additional",
    "FABLE": "Moral tale",
    "FACET": "Side of a gem",
    "FAINT": "Pass out",
    "FAIRY": "Tiny winged being",
    "FAITH": "Belief",
    "FALSE": "Not true",
    "FANCY": "Elaborate",
    "FATAL": "Deadly",
    "FAULT": "Blame",
    "FAVOR": "Kind act",
    "FEAST": "Big meal",
    "FENCE": "Yard barrier",
    "FERRY": "Crossing boat",
    "FETCH": "Go get",
    "FEVER": "High temperature",
    "FIBER": "Roughage",
    "FIELD": "Open meadow",
    "FIERY": "Burning",
    "FIFTH": "Ordinal number",
    "FIFTY": "Half a hundred",
    "FIGHT": "Brawl",
    "FINAL": "Last",
    "FINCH": "Small songbird",
    "FIRST": "Number one",
    "FLAME": "Fire tongue",
    "FLARE": "Bright burst",
    "FLASH": "Brief light",
    "FLEET": "Group of ships",
    "FLESH": "Skin and muscle",
    "FLOAT": "Stay on top of water",
    "FLOCK": "Group of birds",
    "FLOOD": "Overflow",
    "FLOOR": "Room bottom",
    "FLOUR": "Baking powder base",
    "FLUID": "Liquid",
    "FLUTE": "Woodwind",
    "FOCUS": "Concentrate",
    "FORCE": "Power",
    "FORGE": "Blacksmith's shop",
    "FORTY": "Four tens",
    "FORUM": "Discussion board",
    "FOUND": "Discovered",
    "FRAME": "Picture border",
    "FRESH": "New",
    "FROST": "Window ice",
    "FROWN": "Turn down the mouth",
    "FRUIT": "Apple or pear",
    "FUDGE": "Sweet candy",
    "FUNNY": "Amusing",
    "GAVEL": "Judge's hammer",
    "GHOST": "Spooky spirit",
    "GIANT": "Huge being",
    "GIVEN": "Provided",
    "GLARE": "Harsh look",
    "GLAZE": "Donut coating",
    "GLEAM": "Faint shine",
    "GLIDE": "Smooth slide",
    "GLOBE": "World sphere",
    "GLOOM": "Darkness",
    "GLORY": "Great honour",
    "GLOVE": "Hand cover",
    "GOOSE": "Honking bird",
    "GRACE": "Elegance",
    "GRADE": "Score",
    "GRAIN": "Wheat kernel",
    "GRAND": "Impressive",
    "GRANT": "Give, formally",
    "GRAPE": "Vine fruit",
    "GRAPH": "Data chart",
    "GRASP": "Hold tight",
    "GRASS": "Lawn stuff",
    "GRAVE": "Burial plot",
    "GRAVY": "Mashed potato topper",
    "GRAZE": "Feed on grass",
    "GREAT": "Superb",
    "GREED": "Wanting too much",
    "GREEN": "Grass colour",
    "GREET": "Say hello",
    "GRIEF": "Deep sorrow",
    "GRILL": "BBQ device",
    "GRIME": "Ground-in dirt",
    "GRIND": "Crush to powder",
    "GROAN": "Low moan",
    "GROOM": "Wedding man",
    "GROVE": "Small orchard",
    "GROWL": "Low warning sound",
    "GUARD": "Protect",
    "GUAVA": "Tropical fruit",
    "GUESS": "Estimate",
    "GUEST": "Visitor",
    "GUIDE": "Lead the way",
    "GUILD": "Artisan group",
    "HABIT": "Routine",
    "HAPPY": "Cheerful",
    "HARSH": "Severe",
    "HASTE": "Rush",
    "HATCH": "Egg opening",
    "HAVEN": "Safe place",
    "HAZEL": "Nut, or a brown shade",
    "HEDGE": "Shrub fence",
    "HELLO": "Greeting",
    "HENCE": "Therefore",
    "HERON": "Long-legged water bird",
    "HIPPO": "River heavyweight",
    "HOBBY": "Pastime",
    "HONEY": "Bee product",
    "HONOR": "Respect",
    "HORSE": "Galloping animal",
    "HOTEL": "Traveler's lodging",
    "HOUND": "Hunting dog",
    "HOUSE": "Home",
    "HOVER": "Float in place",
    "HUMAN": "Person",
    "HUMID": "Muggy",
    "HUMOR": "Comedy",
    "HURRY": "Speed up",
    "HUSKY": "Northern dog breed",
    "HYENA": "Laughing scavenger",
    "ICING": "Cake topping",
    "IMAGE": "Picture",
    "IMPLY": "Suggest",
    "INDEX": "Back-of-book list",
    "INLET": "Small bay",
    "INNER": "Inside",
    "INPUT": "Contribution",
    "IRONY": "Wry twist",
    "ISSUE": "Problem",
    "IVORY": "Tusk material",
    "JELLY": "Wobbly spread",
    "JEWEL": "Precious stone",
    "JOINT": "Knee or elbow",
    "JOKER": "Wild card",
    "JOLLY": "Merry",
    "JUDGE": "Court official",
    "JUICE": "Orange drink",
    "JUMBO": "Extra large",
    "KARMA": "Cosmic payback",
    "KAYAK": "Paddle boat",
    "KNEEL": "Drop to knees",
    "KNIFE": "Cutting tool",
    "KNOCK": "Rap on a door",
    "KNOLL": "Small hill",
    "LABEL": "Tag",
    "LABOR": "Work",
    "LADLE": "Soup dipper",
    "LAGER": "Pale beer",
    "LANCE": "Knight's spear",
    "LARGE": "Big",
    "LATCH": "Gate fastener",
    "LATER": "Afterwards",
    "LATHE": "Spinning tool",
    "LAUGH": "Chuckle",
    "LAYER": "Stratum",
    "LEARN": "Study",
    "LEASE": "Rental contract",
    "LEASH": "Dog lead",
    "LEAST": "Smallest amount",
    "LEDGE": "Shelf of rock",
    "LEGAL": "Lawful",
    "LEMON": "Sour citrus",
    "LEVEL": "Flat",
    "LEVER": "Pry bar",
    "LIGHT": "Not heavy",
    "LILAC": "Pale purple",
    "LIMBO": "Uncertain state",
    "LINEN": "Bed sheets",
    "LIVER": "Body organ",
    "LLAMA": "Andean pack animal",
    "LOBBY": "Hotel entrance",
    "LOCAL": "Nearby",
    "LODGE": "Mountain inn",
    "LOGIC": "Reasoning",
    "LOOSE": "Not tight",
    "LOWER": "Let down",
    "LOYAL": "Faithful",
    "LUCKY": "Fortunate",
    "LUNAR": "Of the moon",
    "LUNCH": "Midday meal",
    "LYRIC": "Song words",
    "MACAW": "Bright parrot",
    "MAGIC": "Sorcery",
    "MAJOR": "Important",
    "MANGO": "Tropical fruit",
    "MANOR": "Big estate",
    "MAPLE": "Syrup tree",
    "MARCH": "Third month",
    "MARSH": "Wetland",
    "MASON": "Brick worker",
    "MATCH": "Equal, or a fire starter",
    "MAYBE": "Perhaps",
    "MAYOR": "City head",
    "MEDAL": "Winner's disc",
    "MEDIA": "Press",
    "MELON": "Cantaloupe",
    "MERCY": "Compassion",
    "MERGE": "Join together",
    "MERIT": "Worthiness",
    "MERRY": "Jolly",
    "METAL": "Iron or steel",
    "METER": "Parking timer",
    "METRO": "Subway system",
    "MINER": "Coal worker",
    "MINOR": "Small, or underage",
    "MINUS": "Take away",
    "MIRTH": "Laughter",
    "MIXER": "Blender",
    "MODEL": "Pose for photos",
    "MOOSE": "Big antlered deer",
    "MORAL": "Lesson at the end",
    "MOTEL": "Roadside inn",
    "MOTOR": "Engine",
    "MOUNT": "Climb aboard",
    "MOWER": "Lawn cutter",
    "MURAL": "Wall painting",
    "MUSIC": "Song and sound",
    "NAVAL": "Of the fleet",
    "NERVE": "Cheek, or a fibre",
    "NEVER": "Not ever",
    "NICHE": "Specialised spot",
    "NIECE": "Sibling's daughter",
    "NINTH": "Ordinal number",
    "NOBLE": "Honourable",
    "NOISE": "Sound",
    "NOISY": "Loud",
    "NORTH": "Compass direction",
    "NOTCH": "Cut mark",
    "NOVEL": "Book of fiction",
    "NURSE": "Patient carer",
    "NYLON": "Synthetic fabric",
    "OASIS": "Desert spring",
    "OCCUR": "Happen",
    "OCEAN": "Big blue",
    "OFFER": "Put forward",
    "OFTEN": "Frequently",
    "OLIVE": "Pizza topping",
    "ONION": "Layered vegetable",
    "ONSET": "Beginning",
    "OPERA": "Sung drama",
    "ORBIT": "Path around a planet",
    "ORDER": "Command",
    "ORGAN": "Church keyboard",
    "OTHER": "Different one",
    "OTTER": "River swimmer",
    "OUNCE": "Small weight",
    "OZONE": "Protective layer",
    "PAINT": "Wall coating",
    "PANDA": "Bamboo bear",
    "PANEL": "Discussion group",
    "PANIC": "Sudden fear",
    "PAPER": "Sheet for writing",
    "PASTE": "Sticky stuff",
    "PATCH": "Repair square",
    "PATIO": "Backyard slab",
    "PAUSE": "Brief stop",
    "PEACE": "Calm",
    "PEACH": "Fuzzy fruit",
    "PEARL": "Oyster gem",
    "PEDAL": "Bike pusher",
    "PENNY": "Copper coin",
    "PERCH": "Fish, or a roost",
    "PHASE": "Stage",
    "PHONE": "Calling device",
    "PIANO": "Eighty-eight keys",
    "PICKY": "Fussy",
    "PIECE": "Portion",
    "PILOT": "Plane flyer",
    "PINCH": "Small amount",
    "PITCH": "Throw",
    "PIVOT": "Turn on a point",
    "PIXEL": "Screen dot",
    "PLACE": "Spot",
    "PLAID": "Checkered pattern",
    "PLAIN": "Simple",
    "PLANE": "Carpenter's tool",
    "PLANT": "Put in soil",
    "PLATE": "Dinner dish",
    "PLAZA": "Public square",
    "PLEAD": "Beg",
    "PLUCK": "Pull out",
    "PLUMB": "Perfectly vertical",
    "PLUME": "Feather",
    "PLUMP": "Chubby",
    "PLUSH": "Very soft",
    "POINT": "Tip",
    "POLAR": "Of the poles",
    "POLKA": "Dance with dots",
    "PORCH": "Front steps area",
    "POUND": "British currency",
    "POWER": "Strength",
    "PRANK": "Practical joke",
    "PRAWN": "Shrimp cousin",
    "PRESS": "Push down",
    "PRICE": "Cost",
    "PRIDE": "Lion group",
    "PRIME": "Best years",
    "PRINT": "Put on paper",
    "PRIZE": "Reward",
    "PROBE": "Investigate",
    "PRONE": "Lying face down",
    "PROOF": "Evidence",
    "PROSE": "Ordinary writing",
    "PROUD": "Pleased",
    "PROVE": "Show as true",
    "PRUNE": "Dried plum",
    "PULSE": "Heartbeat",
    "PUNCH": "Bowl drink",
    "PUPIL": "Student or eye part",
    "PUPPY": "Baby dog",
    "PURSE": "Handbag",
    "QUACK": "Duck sound",
    "QUAIL": "Small game bird",
    "QUAKE": "Tremble",
    "QUART": "Milk measure",
    "QUEEN": "Royal woman",
    "QUERY": "Question",
    "QUEST": "Long search",
    "QUICK": "Fast",
    "QUIET": "Silent",
    "QUILT": "Patchwork blanket",
    "QUIRK": "Odd trait",
    "QUOTA": "Set share",
    "QUOTE": "Repeat words",
    "RADAR": "Speed detector",
    "RADIO": "Tuner",
    "RAINY": "Wet weather",
    "RALLY": "Big gathering",
    "RANCH": "Cattle farm",
    "RANGE": "Stove, or a spread",
    "RAPID": "Very quick",
    "RATIO": "Proportion",
    "RAVEN": "Black bird of omen",
    "REACH": "Stretch for",
    "REACT": "Respond",
    "REBEL": "Defy authority",
    "RECAP": "Summary",
    "REIGN": "Rule",
    "RELAX": "Unwind",
    "REPLY": "Answer",
    "RHYME": "Poem feature",
    "RIDER": "Horse person",
    "RIDGE": "Narrow crest",
    "RIGHT": "Correct",
    "RIGID": "Stiff",
    "RINSE": "Light wash",
    "RIVAL": "Competitor",
    "RIVER": "Flowing water",
    "ROAST": "Cook in oven, or tease",
    "ROBIN": "Red-breasted bird",
    "ROBOT": "Machine worker",
    "ROCKY": "Stony",
    "RODEO": "Riding show",
    "ROGUE": "Scoundrel",
    "ROMAN": "Of ancient Italy",
    "ROOST": "Where birds rest",
    "ROUGH": "Not smooth",
    "ROUND": "Circular",
    "ROUTE": "Path",
    "ROYAL": "Kingly",
    "RULER": "Measuring stick",
    "RUMOR": "Unverified tale",
    "RURAL": "Countryside",
    "SADLY": "Unfortunately",
    "SAINT": "Holy person",
    "SALAD": "Greens dish",
    "SALON": "Hair studio",
    "SALSA": "Dance or dip",
    "SANDY": "Covered in grains",
    "SATIN": "Smooth fabric",
    "SAUCE": "Pasta topper",
    "SAUNA": "Steam room",
    "SCALE": "Fish plate",
    "SCALP": "Head skin",
    "SCARF": "Neck warmer",
    "SCENE": "View or a fuss",
    "SCENT": "Smell",
    "SCOOP": "Ice cream tool",
    "SCOPE": "Range",
    "SCORE": "Points tally",
    "SCOUT": "Reconnoiter",
    "SCRAP": "Small bit",
    "SCREW": "Fastener",
    "SCRUB": "Clean hard",
    "SEIZE": "Grab",
    "SENSE": "Good judgment",
    "SERVE": "Wait tables",
    "SHACK": "Rough hut",
    "SHADE": "Shadow",
    "SHAFT": "Long passage",
    "SHAKE": "Jiggle",
    "SHALL": "Will, formally",
    "SHAME": "Disgrace",
    "SHAPE": "Form",
    "SHARE": "Split the pie",
    "SHARK": "Ocean predator",
    "SHARP": "Keen edge",
    "SHAVE": "Cut whiskers",
    "SHEEP": "Woolly flock",
    "SHEET": "Bed covering",
    "SHELF": "Book holder",
    "SHELL": "Beach find",
    "SHIFT": "Work period",
    "SHINE": "Gleam",
    "SHINY": "Bright and glossy",
    "SHIRT": "Buttoned top",
    "SHOCK": "Sudden surprise",
    "SHORE": "Beachline",
    "SHORT": "Not tall",
    "SHOUT": "Yell",
    "SHOVE": "Push hard",
    "SHRUB": "Bush",
    "SIEGE": "Long attack",
    "SIGHT": "Vision",
    "SILLY": "Goofy",
    "SINCE": "Because",
    "SIREN": "Alarm",
    "SIXTH": "Ordinal number",
    "SKATE": "Ice glider",
    "SKILL": "Talent",
    "SKIRT": "Knee garment",
    "SKULL": "Head bone",
    "SLANT": "Lean",
    "SLATE": "Rock layer",
    "SLEEP": "Night rest",
    "SLEET": "Icy rain",
    "SLICE": "Cut piece",
    "SLIDE": "Playground chute",
    "SLIME": "Goo",
    "SLOPE": "Incline",
    "SMALL": "Little",
    "SMART": "Clever",
    "SMEAR": "Spread messily",
    "SMILE": "Happy face",
    "SMOKE": "Fire fume",
    "SNACK": "Small bite",
    "SNAKE": "Slithering reptile",
    "SNAIL": "Slow shelled crawler",
    "SNARE": "Trap",
    "SNEAK": "Move quietly",
    "SNIFF": "Nose sound",
    "SNORE": "Sleep sound",
    "SNOWY": "White weather",
    "SOLAR": "Sun power",
    "SOLID": "Firm",
    "SOLVE": "Figure out",
    "SORRY": "Apologetic",
    "SOUND": "Noise",
    "SOUTH": "Compass direction",
    "SPARE": "Extra tire",
    "SPARK": "Small flame",
    "SPAWN": "Hatch eggs",
    "SPEAK": "Talk",
    "SPEED": "Velocity",
    "SPELL": "Write letters, or a magic word",
    "SPEND": "Use money",
    "SPICE": "Flavour powder",
    "SPIKE": "Sharp point",
    "SPILL": "Knock over",
    "SPINE": "Backbone",
    "SPIRE": "Church steeple",
    "SPOKE": "Wheel rod",
    "SPOON": "Scoop utensil",
    "SPORT": "Athletic game",
    "SPRAY": "Fine mist",
    "SQUID": "Ten-armed sea creature",
    "STACK": "Pile",
    "STAFF": "Employees",
    "STAIR": "Step",
    "STAKE": "Wooden post",
    "STALE": "Not fresh",
    "STALL": "Delay, or a market stand",
    "STAMP": "Mail sticker",
    "STAND": "Rise up",
    "STARE": "Look hard",
    "START": "Begin",
    "STATE": "Condition",
    "STEAK": "Beef cut",
    "STEAM": "Kettle vapour",
    "STEEL": "Strong alloy",
    "STEEP": "Very slanted",
    "STEER": "Guide",
    "STICK": "Branch",
    "STIFF": "Not bendy",
    "STILL": "Motionless",
    "STING": "Wasp poke",
    "STOCK": "Market share",
    "STONE": "Rock",
    "STOOL": "Bar seat",
    "STORE": "Shop",
    "STORK": "Baby-delivering bird",
    "STORM": "Bad weather",
    "STORY": "Tale",
    "STOVE": "Cooker",
    "STRAP": "Bag handle",
    "STRAW": "Drinking tube",
    "STRAY": "Wandering animal",
    "STRIP": "Narrow band",
    "STUDY": "Hit the books",
    "STUFF": "Things",
    "STUNT": "Daring feat",
    "STYLE": "Fashion sense",
    "SUGAR": "Sweetener",
    "SUITE": "Hotel rooms group",
    "SUNNY": "Bright weather",
    "SUPER": "Excellent",
    "SURGE": "Sudden rush",
    "SWAMP": "Marshy area",
    "SWEAR": "Take an oath",
    "SWEEP": "Brush the floor",
    "SWEET": "Sugary",
    "SWELL": "Expand",
    "SWEPT": "Sweeped, correctly",
    "SWIFT": "Speedy",
    "SWING": "Playground seat",
    "SWIRL": "Twist around",
    "SWISS": "Alpine, or cheese",
    "SWORD": "Knight's blade",
    "SYRUP": "Pancake topper",
    "TABLE": "Furniture with legs",
    "TACKY": "Cheap looking",
    "TALON": "Eagle's claw",
    "TANGO": "Dance for two",
    "TAPER": "Narrow gradually",
    "TASTE": "Sample",
    "TEACH": "Instruct",
    "TEASE": "Rib playfully",
    "TEMPO": "Musical pace",
    "TENOR": "High male voice",
    "TENSE": "On edge",
    "TENTH": "Ordinal number",
    "THANK": "Express gratitude",
    "THEFT": "Stealing",
    "THEME": "Subject",
    "THICK": "Not thin",
    "THIEF": "Robber",
    "THING": "Object",
    "THINK": "Use your brain",
    "THORN": "Rose prickle",
    "THREE": "One more than two",
    "THREW": "Tossed",
    "THUMB": "Hand digit",
    "TIARA": "Small crown",
    "TIGER": "Striped cat",
    "TIMER": "Kitchen countdown",
    "TITLE": "Name of a book",
    "TOAST": "Brown bread, or a speech",
    "TODAY": "This very day",
    "TOKEN": "Subway coin",
    "TONIC": "Gin partner",
    "TOOTH": "Molar",
    "TOPAZ": "Yellow gem",
    "TOPIC": "Subject",
    "TORCH": "Stick with fire",
    "TOTAL": "Sum",
    "TOTEM": "Pole with carvings",
    "TOUCH": "Feel",
    "TOUGH": "Hard to chew",
    "TOWEL": "Bath drying cloth",
    "TOWER": "Tall structure",
    "TRACE": "Faint mark",
    "TRACK": "Racing path",
    "TRADE": "Swap",
    "TRAIL": "Woodland path",
    "TRAIN": "Railway cars",
    "TRAIT": "Characteristic",
    "TRASH": "Garbage",
    "TREAT": "Special reward",
    "TREND": "Fashion direction",
    "TRIAL": "Court case",
    "TRIBE": "Group of people",
    "TRICK": "Magic act",
    "TROUT": "Stream fish",
    "TRUCK": "Hauler",
    "TRULY": "Genuinely",
    "TRUNK": "Tree stem, or a case",
    "TRUTH": "Fact",
    "TULIP": "Spring bulb flower",
    "TUNIC": "Long shirt",
    "TUTOR": "Private teacher",
    "TWANG": "Nasal sound",
    "TWEAK": "Small adjust",
    "TWICE": "Two times",
    "TWINE": "Thin string",
    "TWIRL": "Spin around",
    "TWIST": "Turn sharply",
    "UNCLE": "Parent's brother",
    "UNDER": "Beneath",
    "UNIFY": "Bring together",
    "UNION": "Alliance",
    "UNITE": "Join forces",
    "UNITY": "Togetherness",
    "UNTIE": "Loosen a knot",
    "UNTIL": "Up to a point",
    "UPPER": "Higher",
    "UPSET": "Distressed",
    "URBAN": "Of a city",
    "USAGE": "Way it's used",
    "USHER": "Theatre guide",
    "USUAL": "Customary",
    "UTTER": "Say out loud",
    "VAGUE": "Unclear",
    "VALID": "Sound and legal",
    "VALUE": "Worth",
    "VALVE": "Pipe controller",
    "VAPOR": "Mist",
    "VAULT": "Bank safe",
    "VENOM": "Snake poison",
    "VENUE": "Event place",
    "VERGE": "Edge",
    "VERSE": "Poem part",
    "VIDEO": "Filmed clip",
    "VILLA": "Country house",
    "VINYL": "Record material",
    "VIOLA": "String instrument",
    "VIPER": "Venomous snake",
    "VIRUS": "Tiny germ",
    "VISIT": "Stop by",
    "VISTA": "Wide view",
    "VITAL": "Essential",
    "VIVID": "Bright and clear",
    "VOCAL": "Outspoken",
    "VOICE": "Speaking sound",
    "VOTER": "Ballot caster",
    "VOWEL": "A, E, I, O or U",
    "WAGER": "Bet",
    "WAGON": "Pull cart",
    "WAIST": "Middle of the body",
    "WALTZ": "Three-quarter dance",
    "WASTE": "Squander",
    "WATCH": "Wrist clock",
    "WATER": "H2O",
    "WEARY": "Very tired",
    "WEAVE": "Make cloth",
    "WEIGH": "Put on a scale",
    "WEIRD": "Strange",
    "WHALE": "Ocean giant",
    "WHARF": "Loading dock",
    "WHEAT": "Bread grain",
    "WHEEL": "Circle that rolls",
    "WHERE": "In what place",
    "WHICH": "What one",
    "WHILE": "During the time that",
    "WHIRL": "Spin fast",
    "WHISK": "Egg beater",
    "WHITE": "Snow colour",
    "WHOLE": "Entire",
    "WHOSE": "Belonging to whom",
    "WIDEN": "Make broader",
    "WIDOW": "Surviving spouse",
    "WIDTH": "Broadness",
    "WIELD": "Use, as a tool",
    "WINCH": "Crank hoist",
    "WINDY": "Breezy",
    "WITCH": "Broom flyer",
    "WITTY": "Cleverly funny",
    "WOMAN": "Adult female",
    "WORLD": "The whole planet",
    "WORRY": "Fret",
    "WORSE": "Less good",
    "WORST": "Least good",
    "WORTH": "Value",
    "WOUND": "Injury",
    "WOVEN": "Made on a loom",
    "WRATH": "Fury",
    "WRECK": "Ruin",
    "WRIST": "Hand joint",
    "WRITE": "Put words down",
    "WRONG": "Incorrect",
    "WROTE": "Writed, correctly",
    "YACHT": "Luxury boat",
    "YEAST": "Bread riser",
    "YIELD": "Give way",
    "YOUNG": "Not old",
    "YOUTH": "Early years",
    "ZEBRA": "Striped equine",
    "ZESTY": "Full of flavour",

    # ---- 6 letters ----
    "ALMOND": "Nut in a marzipan",
    "ANIMAL": "Living creature",
    "ANTHEM": "Stirring song",
    "ARCADE": "Game hall",
    "ARTIST": "Painter",
    "ASPECT": "Side of a matter",
    "AUTHOR": "Book writer",
    "BALLAD": "Slow song",
    "BAMBOO": "Panda food",
    "BANANA": "Yellow fruit",
    "BARREL": "Big cask",
    "BASKET": "Woven container",
    "BEACON": "Guiding light",
    "BEAVER": "Dam builder",
    "BEETLE": "Hard-shelled insect",
    "BISTRO": "Small eatery",
    "BOTTLE": "Glass container",
    "BRANCH": "Tree limb",
    "BRIDGE": "River crosser",
    "BRONZE": "Third-place metal",
    "BUCKET": "Pail",
    "BUDGET": "Spending plan",
    "BUFFALO": "Shaggy plains beast",
    "BULLET": "Gun projectile",
    "BUNKER": "Golf sand trap",
    "BURDEN": "Heavy load",
    "BUREAU": "Dresser",
    "BUTTON": "Shirt fastener",
    "CAMERA": "Photo device",
    "CANDLE": "Wax light",
    "CANOPY": "Overhead cover",
    "CANYON": "Deep gorge",
    "CARROT": "Bunny's snack",
    "CASTLE": "Fortified home",
    "CATTLE": "Cows collectively",
    "CAVERN": "Big cave",
    "CELLAR": "Basement",
    "CEMENT": "Setting powder",
    "CENSUS": "Population count",
    "CENTER": "Middle",
    "CHERRY": "Pie fruit with a pit",
    "CIRCUS": "Big tent show",
    "COFFEE": "Morning cup",
    "COLLAR": "Shirt neck",
    "COLONY": "Settlement",
    "COLUMN": "Pillar",
    "COMEDY": "Humour",
    "COPPER": "Penny metal",
    "CORNER": "Where walls meet",
    "COTTON": "Soft fibre",
    "COUGAR": "Big cat of the hills",
    "COUSIN": "Relative",
    "COYOTE": "Desert howler",
    "CRADLE": "Baby bed",
    "CRATER": "Volcano dip",
    "CRAYON": "Wax colour stick",
    "CREDIT": "Card, or praise",
    "CRUISE": "Sea holiday",
    "CUDDLE": "Snuggle",
    "CURFEW": "Set time in",
    "CURSOR": "Screen arrow",
    "CUSTOM": "Tradition",
    "DAGGER": "Short blade",
    "DANGER": "Risk",
    "DEALER": "Card handler",
    "DEBATE": "Formal argument",
    "DECADE": "Ten years",
    "DECODE": "Break a cipher",
    "DEFEAT": "Loss",
    "DEGREE": "Temperature unit",
    "DELETE": "Erase",
    "DELUXE": "Top version",
    "DENIAL": "Refusal",
    "DEPLOY": "Send out",
    "DEPUTY": "Second in command",
    "DESIGN": "Plan it out",
    "DESIRE": "Strong want",
    "DETAIL": "Small point",
    "DEVICE": "Gadget",
    "DIGEST": "Break down food",
    "DINNER": "Evening meal",
    "DOLLAR": "Buck",
    "DONKEY": "Braying animal",
    "DOUBLE": "Twice as much",
    "DRAGON": "Fire breather",
    "DRAWER": "Dresser part",
    "DRIVER": "Wheel holder",
    "EASILY": "With no trouble",
    "EDITOR": "Copy fixer",
    "EFFECT": "Result",
    "EITHER": "One or the other",
    "ELEVEN": "Football team size",
    "EMBLEM": "Symbol",
    "EMPIRE": "A big domain",
    "ENABLE": "Allow",
    "ENERGY": "Get-up-and-go",
    "ENGINE": "Car motor",
    "ENSURE": "Make certain",
    "ENTIRE": "Whole",
    "ESCAPE": "Get away",
    "ESTATE": "Big property",
    "ETHICS": "Moral code",
    "EXCESS": "Too much",
    "EXPAND": "Grow larger",
    "EXPERT": "Authority",
    "EXPORT": "Ship abroad",
    "EXTEND": "Stretch out",
    "FABRIC": "Cloth",
    "FALCON": "Diving hunter",
    "FAMINE": "Food shortage",
    "FATHER": "Dad",
    "FELINE": "Cat family",
    "FIDDLE": "Violin",
    "FIGURE": "Shape",
    "FILTER": "Coffee screen",
    "FINGER": "Hand digit",
    "FINISH": "End it",
    "FISCAL": "Money-related",
    "FLAVOR": "Taste",
    "FLOWER": "Bloom",
    "FOLDER": "Paper holder",
    "FOLLOW": "Go after",
    "FOREST": "Woods",
    "FORMAT": "Layout",
    "FOSSIL": "Ancient remains",
    "FOSTER": "Encourage",
    "FREEZE": "Turn to ice",
    "FRIDGE": "Cool kitchen box",
    "FRINGE": "Edge",
    "FUTURE": "Time to come",
    "GADGET": "Little tool",
    "GALAXY": "Star system",
    "GALLON": "Milk jug size",
    "GARAGE": "Car shelter",
    "GARDEN": "Plant patch",
    "GARLIC": "Bread bulb",
    "GATHER": "Assemble",
    "GINGER": "Spicy root",
    "GIRDER": "Steel beam",
    "GLIDER": "Soaring plane",
    "GOBLIN": "Small ugly imp",
    "GOLDEN": "Bright yellow",
    "GOSPEL": "Church reading",
    "GRAVEL": "Driveway stones",
    "GROCER": "Food seller",
    "GROOVE": "Record's ridge",
    "GROUND": "Earth underfoot",
    "GUITAR": "Six-string",
    "GUTTER": "Street drain",
    "HAMMER": "Nail driver",
    "HANDLE": "Grip, or a name",
    "HANGAR": "Plane shelter",
    "HARBOR": "Port",
    "HATRED": "Intense dislike",
    "HAZARD": "Danger",
    "HELMET": "Head protection",
    "HERMIT": "Lone dweller",
    "HIDDEN": "Tucked away",
    "HOCKEY": "Ice sport",
    "HOLLOW": "Empty inside",
    "HOMELY": "Plain and cozy",
    "HONEST": "Truthful",
    "HUNTER": "Quarry chaser",
    "HURDLE": "Track barrier",
    "ICICLE": "Hanging ice spike",
    "IGNORE": "Pay no mind",
    "IMPACT": "Big effect",
    "IMPORT": "Bring in",
    "INCOME": "Earnings",
    "INDOOR": "Inside a building",
    "INJECT": "Put in with a needle",
    "INJURY": "Wound",
    "INSECT": "Bug",
    "INSIDE": "Interior",
    "INTACT": "Unbroken",
    "INVENT": "Create anew",
    "INWARD": "Toward the middle",
    "ISLAND": "Land in water",
    "JACKET": "Blazer",
    "JAGUAR": "Spotted cat",
    "JERSEY": "Sports shirt",
    "JIGSAW": "Puzzle with blades",
    "JUNGLE": "Dense forest",
    "JUNIOR": "Younger",
    "KETTLE": "Boiler for tea",
    "KIDNEY": "Bean-shaped organ",
    "KITTEN": "Baby cat",
    "KNIGHT": "Armoured rider",
    "LADDER": "Climbing steps",
    "LAGOON": "Shallow pool",
    "LAPTOP": "Portable computer",
    "LAUREL": "Wreath leaf",
    "LAWYER": "Legal expert",
    "LEADER": "Person in front",
    "LEGACY": "What you leave behind",
    "LEGEND": "Old tale, or a key",
    "LENGTH": "How long",
    "LESSON": "Class unit",
    "LETTER": "Mail item",
    "LINGER": "Hang around",
    "LIZARD": "Scaly crawler",
    "LOCKET": "Pendant",
    "LOVELY": "Delightful",
    "LUMBER": "Timber",
    "MAGNET": "Fridge sticker",
    "MANNER": "Way of acting",
    "MARBLE": "Glass shooter, or stone",
    "MARGIN": "Page edge",
    "MARINA": "Boat harbour",
    "MARKET": "Buy and sell",
    "MARROW": "Bone centre",
    "MASCOT": "Team symbol",
    "MATTER": "Be important",
    "MEADOW": "Grassy field",
    "MEDIAN": "Middle value",
    "MEDIUM": "In the middle",
    "MELODY": "Tune",
    "MEMBER": "One of the group",
    "MEMORY": "Recollection",
    "MENTOR": "Trusted advisor",
    "MERLOT": "Red wine grape",
    "METHOD": "Way of doing",
    "MIDDLE": "Centre",
    "MINNOW": "Tiny fish",
    "MINUTE": "Sixty seconds",
    "MIRROR": "Reflective glass",
    "MISFIT": "Square peg",
    "MODERN": "Up to date",
    "MODEST": "Humble",
    "MOLTEN": "Melted",
    "MONKEY": "Tree climber with a tail",
    "MORTAL": "Subject to death",
    "MOSAIC": "Tile art",
    "MOTIVE": "Reason why",
    "MUFFIN": "Breakfast cake",
    "MUSEUM": "Exhibit hall",
    "MUZZLE": "Snout cover",
    "MYSTIC": "Spiritual seer",
    "NARROW": "Not wide",
    "NATURE": "Outdoors",
    "NECTAR": "Flower juice",
    "NEEDLE": "Sewing spike",
    "NEPHEW": "Sibling's son",
    "NETTLE": "Stinging plant",
    "NIBBLE": "Small bite",
    "NICKEL": "Five-cent coin",
    "NOODLE": "Pasta strand",
    "NOTICE": "See, or a sign",
    "NOZZLE": "Hose end",
    "NUGGET": "Gold lump",
    "NUMBER": "Digit",
    "OBJECT": "Thing",
    "OBSESS": "Can't stop thinking",
    "OCCUPY": "Fill up",
    "OCTAVE": "Eight notes",
    "OFFICE": "Desk workplace",
    "ONLINE": "Connected up",
    "OPTION": "Choice",
    "ORANGE": "Citrus fruit",
    "ORCHID": "Fancy flower",
    "ORIOLE": "Orange songbird",
    "ORPHAN": "Parentless child",
    "OUTFIT": "Clothing set",
    "OUTLAW": "Bandit",
    "OUTPUT": "Produced amount",
    "OYSTER": "Pearl source",
    "PADDLE": "Canoe mover",
    "PALACE": "Royal home",
    "PAPAYA": "Tropical melon",
    "PARADE": "March with floats",
    "PARCEL": "Package",
    "PARROT": "Copying bird",
    "PASTRY": "Bakery treat",
    "PATROL": "Guard route",
    "PATRON": "Regular customer",
    "PEBBLE": "Small stone",
    "PENCIL": "Graphite writer",
    "PEOPLE": "Folks",
    "PEPPER": "Salt's partner",
    "PERIOD": "Full stop",
    "PERMIT": "Allow, or a pass",
    "PERSON": "Human being",
    "PHRASE": "Group of words",
    "PICKLE": "Brined cucumber",
    "PIGEON": "City bird",
    "PILLAR": "Column",
    "PILLOW": "Head cushion",
    "PIRATE": "Sea robber",
    "PISTOL": "Handgun",
    "PISTON": "Engine part",
    "PLANET": "Mars or Venus",
    "PLAQUE": "Wall plate",
    "PLASMA": "Blood fluid",
    "PLIERS": "Gripping tool",
    "PLUNGE": "Dive in",
    "POCKET": "Pant pouch",
    "PODIUM": "Winner's stand",
    "POETRY": "Verse art",
    "POLICE": "The force",
    "POLICY": "Rule set",
    "POPLAR": "Fast-growing tree",
    "PORTAL": "Grand gateway",
    "POSTER": "Wall print",
    "POTATO": "Spud",
    "POWDER": "Fine dust",
    "PRAYER": "Spoken worship",
    "PRETTY": "Attractive",
    "PRINCE": "Royal son",
    "PRISON": "Jail",
    "PROFIT": "Money made",
    "PROMPT": "Cue",
    "PROPER": "Correct",
    "PUNISH": "Penalise",
    "PUZZLE": "Brain teaser",
    "PYTHON": "Big constrictor",
    "QUARTZ": "Clock crystal",
    "QUIVER": "Arrow case",
    "RABBIT": "Long-eared hopper",
    "RADIUS": "Half a diameter",
    "RAFFLE": "Prize draw",
    "RAGGED": "Torn",
    "RANDOM": "By chance",
    "RANSOM": "Kidnap demand",
    "RATTLE": "Shake noisily",
    "REASON": "Cause",
    "RECALL": "Remember",
    "RECESS": "Play break",
    "RECIPE": "Cooking instructions",
    "RECORD": "Vinyl disc",
    "REFLEX": "Knee jerk",
    "REGION": "Area",
    "RELIEF": "Comfort",
    "REMAIN": "Stay behind",
    "REMEDY": "Cure",
    "REMOTE": "TV clicker",
    "REPAIR": "Fix",
    "REPEAT": "Say again",
    "REPORT": "Written account",
    "RESCUE": "Save",
    "RESORT": "Holiday spot",
    "RESULT": "Outcome",
    "RETAIL": "Shop selling",
    "RETURN": "Come back",
    "REVEAL": "Show",
    "REVIEW": "Critique",
    "REWARD": "Bounty",
    "RIBBON": "Gift tie",
    "RIDDLE": "Puzzling question",
    "RIPPLE": "Small wave",
    "RITUAL": "Custom",
    "ROCKET": "Moon launcher",
    "RODENT": "Rat or mouse",
    "ROSTER": "Duty list",
    "ROTATE": "Turn",
    "ROTTEN": "Decayed",
    "RUBBER": "Elastic material",
    "RUBBLE": "Broken stone",
    "RUDDER": "Boat steering fin",
    "RUGGED": "Tough and rough",
    "RUMBLE": "Low sound",
    "RUNNER": "Racer",
    "SADDLE": "Horse seat",
    "SAFARI": "Wildlife trip",
    "SALMON": "Pink fish",
    "SALOON": "Western bar",
    "SALUTE": "Military greeting",
    "SAMPLE": "Small taste",
    "SANDAL": "Open shoe",
    "SAVAGE": "Fierce",
    "SAVORY": "Not sweet",
    "SCARCE": "Hard to find",
    "SCHOOL": "Learning place",
    "SCOTCH": "Tape brand",
    "SCREEN": "Display",
    "SCRIPT": "Written lines",
    "SCULPT": "Carve",
    "SEASON": "Spring or fall",
    "SECOND": "Runner-up",
    "SECRET": "Kept quiet",
    "SECTOR": "Zone",
    "SECURE": "Safe",
    "SEESAW": "Up-and-down board",
    "SENATE": "Lawmaking body",
    "SENIOR": "Older",
    "SENSOR": "Detector",
    "SERIAL": "In a series",
    "SERMON": "Church talk",
    "SETTLE": "Resolve",
    "SHADOW": "Dark shape",
    "SHIELD": "Protection",
    "SHIVER": "Shake from cold",
    "SHORTS": "Summer wear",
    "SHOVEL": "Dig tool",
    "SHRINE": "Holy place",
    "SHRINK": "Get smaller",
    "SICKLE": "Curved blade",
    "SIGNAL": "Sign",
    "SILENT": "Noiseless",
    "SILVER": "Second-place metal",
    "SIMPLE": "Easy",
    "SINGER": "Vocalist",
    "SKETCH": "Rough drawing",
    "SLEDGE": "Snow slider",
    "SLEEVE": "Arm cover",
    "SLIPPER": "House shoe",
    "SLOGAN": "Catchphrase",
    "SMOOTH": "Even surface",
    "SOCCER": "Football, abroad",
    "SOCIAL": "Gregarious",
    "SODIUM": "Salt element",
    "SOFTEN": "Make gentle",
    "SOLEMN": "Serious",
    "SONATA": "Classical piece",
    "SOONER": "Earlier",
    "SPIDER": "Web spinner",
    "SPINAL": "Of the backbone",
    "SPIRIT": "Ghost, or pluck",
    "SPLASH": "Water sound",
    "SPONGE": "Absorbent pad",
    "SPRAIN": "Joint twist",
    "SPRING": "Coil, or the season",
    "SPRINT": "Short dash",
    "SPROUT": "Bean shoot",
    "SQUARE": "Four-sided shape",
    "SQUEAK": "Mouse sound",
    "STABLE": "Horse house",
    "STAPLE": "Fastener",
    "STARVE": "Go hungry",
    "STATIC": "Radio crackle",
    "STATUE": "Carved figure",
    "STEADY": "Stable",
    "STEREO": "Sound system",
    "STICKY": "Tacky to touch",
    "STITCH": "Suture",
    "STRAIN": "Overwork",
    "STREAM": "Small river",
    "STREET": "Road",
    "STRESS": "Pressure",
    "STRIKE": "Hit, or a walkout",
    "STRING": "Twine",
    "STRIVE": "Try hard",
    "STROLL": "Leisurely walk",
    "STRONG": "Powerful",
    "STUCCO": "Wall plaster",
    "STUDIO": "Artist's room",
    "SUBMIT": "Hand in",
    "SUBWAY": "Underground train",
    "SUMMER": "Warm season",
    "SUMMIT": "Top of a mountain",
    "SUNSET": "Evening glow",
    "SUPERB": "Excellent",
    "SUPPLY": "Provide",
    "SURVEY": "Questionnaire",
    "SWITCH": "Toggle",
    "SYMBOL": "Sign",
    "SYSTEM": "Method",
    "TABLET": "iPad, generically",
    "TALENT": "Gift",
    "TAMALE": "Husked treat",
    "TANDEM": "Bike for two",
    "TANGLE": "Knot up",
    "TARGET": "Goal",
    "TARIFF": "Import tax",
    "TAUGHT": "Educated",
    "TEMPER": "Mood",
    "TEMPLE": "Sacred building",
    "TENANT": "Renter",
    "TENDER": "Gentle",
    "TENNIS": "Racket sport",
    "THANKS": "Gratitude",
    "THEORY": "Explanation",
    "THIRST": "Dry feeling",
    "THRONE": "Royal seat",
    "THRUST": "Push hard",
    "TICKET": "Entry slip",
    "TIMBER": "Cut wood",
    "TINSEL": "Shiny trim",
    "TOFFEE": "Chewy sweet",
    "TOMATO": "Salad fruit",
    "TONGUE": "Taste organ",
    "TORQUE": "Twisting force",
    "TOUCAN": "Big-billed bird",
    "TRAGIC": "Very sad",
    "TRAVEL": "Go places",
    "TREATY": "Peace deal",
    "TREBLE": "Three times",
    "TRENCH": "Deep ditch",
    "TRIFLE": "Small amount",
    "TRIPLE": "Threefold",
    "TRIVIA": "Quiz facts",
    "TROPHY": "Cup award",
    "TROPIC": "Hot latitude",
    "TROWEL": "Gardening scoop",
    "TRUDGE": "Walk heavily",
    "TUMBLE": "Fall over",
    "TUNDRA": "Frozen plain",
    "TUNNEL": "Underground passage",
    "TURKEY": "Big bird",
    "TURTLE": "Shelled swimmer",
    "TUXEDO": "Formal suit",
    "TWITCH": "Sudden jerk",
    "TYCOON": "Business titan",
    "UMPIRE": "Official in blue",
    "UNIQUE": "One of a kind",
    "UNITED": "Joined as one",
    "UNLOCK": "Open with a key",
    "UNPACK": "Empty a suitcase",
    "UNREST": "Trouble",
    "UPBEAT": "Cheerful",
    "UPGRADE": "Improve",
    "UPHILL": "Against the slope",
    "UPRIGHT": "Vertical, or honest",
    "UPROAR": "Loud protest",
    "UPSCALE": "High-end",
    "UPTIGHT": "Tense",
    "URGENT": "Needs doing now",
    "UTOPIA": "Perfect place",
    "VACANT": "Empty",
    "VACUUM": "Sucking cleaner",
    "VALLEY": "Land between hills",
    "VANISH": "Disappear",
    "VANITY": "Too much pride",
    "VECTOR": "Direction arrow",
    "VELVET": "Plush fabric",
    "VENDOR": "Seller",
    "VERBAL": "Spoken",
    "VERIFY": "Check",
    "VERSUS": "Against",
    "VESSEL": "Ship, or a pot",
    "VICTIM": "Injured party",
    "VICTOR": "Winner",
    "VIEWER": "Watcher",
    "VIOLET": "Purple shade",
    "VIOLIN": "Four-string",
    "VIRTUE": "Moral goodness",
    "VISION": "Sight",
    "VISUAL": "Relating to sight",
    "VOLUME": "Loudness",
    "VOYAGE": "Long trip",
    "WALNUT": "Wrinkled nut",
    "WALRUS": "Tusked sea mammal",
    "WANDER": "Roam",
    "WARMTH": "Cozy feeling",
    "WALLET": "Bill holder",
    "WEALTH": "Richness",
    "WEAPON": "Arm",
    "WEASEL": "Sneaky animal",
    "WEAVER": "Cloth maker",
    "WEIGHT": "Heaviness",
    "WHISPER": "Quiet speech",
    "WICKED": "Evil",
    "WILLOW": "Weeping tree",
    "WINDOW": "Glass opening",
    "WINNER": "Champion",
    "WINTER": "Cold season",
    "WISDOM": "Good judgment",
    "WITHIN": "Inside",
    "WIZARD": "Magic man",
    "WONDER": "Awe",
    "WOOLEN": "Of wool",
    "WORKER": "Employee",
    "WORTHY": "Deserving",
    "WRENCH": "Bolt turner",
    "WRITER": "Author",
    "YELLOW": "Lemon colour",
    "YOGURT": "Cultured dairy",
    "ZIGZAG": "Sharp turn pattern",
    "ZODIAC": "Star sign set",
    "ZOMBIE": "Walking dead",

    # ---- 7 letters ----
    "ABANDON": "Leave behind",
    "ACADEMY": "School of note",
    "ACHIEVE": "Get it done",
    "ACROBAT": "Flipping performer",
    "ADDRESS": "Where you live, or a speech",
    "ADVANCE": "Move forward",
    "AIRPORT": "Flight hub",
    "ALMANAC": "Yearly reference",
    "ANCHOVY": "Salty pizza fish",
    "ANCIENT": "Very old",
    "ANOTHER": "One more",
    "ANXIETY": "Worry",
    "APOLOGY": "Sorry note",
    "APRICOT": "Orange stone fruit",
    "ARCHERY": "Bow and arrow sport",
    "ARRIVAL": "Coming in",
    "ARTICLE": "Written piece",
    "ASPHALT": "Road surface",
    "ATHLETE": "Sport pro",
    "AUCTION": "Bidding sale",
    "AVERAGE": "Ordinary",
    "BALCONY": "Apartment ledge",
    "BANDAGE": "Wound wrap",
    "BANQUET": "Banquet",
    "BARGAIN": "Good deal",
    "BARRIER": "Obstacle",
    "BASTION": "Stronghold",
    "BATTERY": "Power cell",
    "BEDROCK": "Solid base",
    "BICYCLE": "Two-wheeler",
    "BISCUIT": "Crumbly bread",
    "BLANKET": "Bed cover",
    "BLOSSOM": "Bloom",
    "BOULDER": "Big rock",
    "BRIEFLY": "For a short time",
    "BROTHER": "Sibling",
    "BROWNIE": "Chocolate square",
    "CABINET": "Kitchen cupboard",
    "CAMPING": "Tent holiday",
    "CAPTAIN": "Team leader",
    "CARAVAN": "Traveling group",
    "CAREFUL": "Watch it",
    "CARRIER": "Phone network",
    "CASCADE": "Waterfall",
    "CATALOG": "Product list",
    "CATWALK": "Model's runway",
    "CEILING": "Room top",
    "CENTRAL": "In the middle",
    "CENTURY": "Hundred years",
    "CERTAIN": "Sure",
    "CHAMBER": "Room",
    "CHAPTER": "Book division",
    "CHARITY": "Good cause",
    "CHARTER": "Hired bus or boat",
    "CHEDDAR": "Orange cheese",
    "CHEETAH": "Spotted sprinter",
    "CHEMIST": "Drugstore worker, abroad",
    "CHERISH": "Hold dear",
    "CHICKEN": "Clucking bird",
    "CHIMNEY": "Smoke stack",
    "CIRCUIT": "Electrical loop",
    "CITADEL": "Fortress",
    "CLARIFY": "Explain",
    "CLASSIC": "Timeless",
    "CLIMATE": "Weather pattern",
    "CLIMBER": "Upward goer",
    "CLOTHES": "Garments",
    "CLUSTER": "Tight group",
    "COCONUT": "Tropical nut",
    "COLLEGE": "Uni",
    "COLLIDE": "Crash into",
    "COLONEL": "Rank above major",
    "COMFORT": "Ease",
    "COMMAND": "Order",
    "COMPACT": "Small and neat",
    "COMPANY": "Business",
    "COMPASS": "Direction finder",
    "CONCEPT": "Idea",
    "CONCERT": "Live show",
    "CONDUCT": "Behaviour",
    "CONNECT": "Link up",
    "CONQUER": "Defeat",
    "CONSENT": "Permission",
    "CONTACT": "Get in touch",
    "CONTROL": "Command",
    "CONVERT": "Change over",
    "COOKING": "Making food",
    "CORRECT": "Right",
    "COSTUME": "Fancy dress",
    "COTTAGE": "Small house",
    "COUNCIL": "Local government",
    "COUNSEL": "Advice",
    "COUNTRY": "Nation",
    "COURAGE": "Bravery",
    "CRACKER": "Soup side",
    "CRANIUM": "Skull",
    "CRAVING": "Strong urge",
    "CREATOR": "Maker",
    "CRICKET": "Chirping sport",
    "CRIMSON": "Deep red",
    "CRITTER": "Little creature",
    "CROQUET": "Mallet lawn game",
    "CRUCIAL": "Critical",
    "CRUISER": "Patrol boat",
    "CRUMBLE": "Fall apart",
    "CRUSADE": "Holy war",
    "CUBICLE": "Office box",
    "CUISINE": "Cooking style",
    "CULTURE": "Way of life",
    "CUPCAKE": "Frosted treat",
    "CURRENT": "Flow of water",
    "CURTAIN": "Window drape",
    "CUSHION": "Sofa pad",
    "CYCLONE": "Spinning storm",
    "DAZZLED": "Blinded by light",
    "DECEIVE": "Mislead",
    "DECIMAL": "Point number",
    "DEFENSE": "Protection",
    "DELIGHT": "Great joy",
    "DELIVER": "Bring it",
    "DENTIST": "Tooth doctor",
    "DEPOSIT": "Upfront payment",
    "DESCENT": "Coming down",
    "DESERVE": "Earn it",
    "DESKTOP": "Computer on a table",
    "DESTINY": "Fate",
    "DESTROY": "Wreck",
    "DEVELOP": "Grow",
    "DIAGRAM": "Labeled drawing",
    "DIAMOND": "Baseball field, or a gem",
    "DICTATE": "Command",
    "DIGITAL": "Not analog",
    "DILEMMA": "Tough choice",
    "DISCUSS": "Talk over",
    "DISEASE": "Illness",
    "DISMISS": "Send away",
    "DISPLAY": "Show",
    "DISPUTE": "Argument",
    "DISTANT": "Far off",
    "DOLPHIN": "Clicking swimmer",
    "DOORWAY": "Way in",
    "DRIZZLE": "Light rain",
    "DROUGHT": "Long dry spell",
    "DURABLE": "Long-lasting",
    "DUSTPAN": "Sweep receiver",
    "DYNAMIC": "Energetic",
    "DYNASTY": "Ruling line",
    "EARNEST": "Sincere",
    "EASTERN": "Of the east",
    "ECLIPSE": "Sun blocker",
    "ECOLOGY": "Environmental study",
    "ELDERLY": "Old",
    "ELEGANT": "Graceful",
    "ELEVATE": "Raise up",
    "EMBASSY": "Diplomatic office",
    "EMBRACE": "Hug",
    "EMERALD": "Green gem",
    "EMPATHY": "Feeling for others",
    "EMPEROR": "Ruler",
    "ENDLESS": "Without stop",
    "ENDORSE": "Back a brand",
    "ENFORCE": "Make people obey",
    "ENHANCE": "Improve",
    "ENVELOP": "Wrap up",
    "EQUATOR": "Middle of the world",
    "ESSENCE": "Core nature",
    "ETERNAL": "Forever",
    "EVENING": "Night's start",
    "EXAMINE": "Look over",
    "EXAMPLE": "Instance",
    "EXHAUST": "Tire out",
    "EXPLAIN": "Make clear",
    "EXPLODE": "Blow up",
    "EXPLORE": "Look around",
    "EXPRESS": "Fast train, or to say",
    "EXTREME": "Radical",
    "FACULTY": "Teaching staff",
    "FANFARE": "Trumpet blast",
    "FANTASY": "Daydream",
    "FASHION": "Style",
    "FEATHER": "Bird's light coat",
    "FEDERAL": "National, in the US",
    "FENCING": "Sword sport",
    "FERTILE": "Rich soil",
    "FICTION": "Made-up stories",
    "FIFTEEN": "Three fives",
    "FIGHTER": "Brawler",
    "FINALLY": "At last",
    "FIREFLY": "Glowing bug",
    "FISHING": "Angling",
    "FISSURE": "Deep crack",
    "FITNESS": "Health",
    "FLANNEL": "Soft shirt",
    "FLOWERS": "Bouquet contents",
    "FOREVER": "Always",
    "FORGIVE": "Let it go",
    "FORMULA": "Recipe in math",
    "FORTUNE": "Wealth, or luck",
    "FORWARD": "Ahead",
    "FOUNDER": "Person who started it",
    "FRAGILE": "Handle with care",
    "FREEDOM": "Liberty",
    "FREEZER": "Ice box",
    "FREIGHT": "Cargo",
    "FRONTIER": "Edge of settlement",
    "FURNACE": "Home heater",
    "GARBAGE": "Trash",
    "GATEWAY": "Entry point",
    "GAZELLE": "Fast antelope",
    "GENERAL": "Broad, or a commander",
    "GENESIS": "Beginning",
    "GENUINE": "Real deal",
    "GEOLOGY": "Rock study",
    "GESTURE": "Motion, or a kind act",
    "GIRAFFE": "Tall spotted one",
    "GLACIER": "Slow ice river",
    "GLASSES": "Spectacles",
    "GLIMMER": "Faint shine",
    "GLITTER": "Sparkle",
    "GORILLA": "Big ape",
    "GRAMMAR": "Language rules",
    "GRANITE": "Speckled rock",
    "GRANOLA": "Oat cluster snack",
    "GREATLY": "Very much",
    "GRENADE": "Small bomb",
    "GRIDDLE": "Pancake pan",
    "GRINDER": "Coffee mill",
    "GROCERY": "Weekly shop",
    "GROWNUP": "Adult",
    "GRUMBLE": "Complain",
    "GUITARS": "Six-strings, plural",
    "GYMNAST": "Flipping athlete",
    "HABITAT": "Natural home",
    "HAIRCUT": "Trim for the top",
    "HALFWAY": "Midpoint",
    "HALLWAY": "Corridor",
    "HAMMOCK": "Backyard nap spot",
    "HANDFUL": "Small amount",
    "HAPPILY": "With joy",
    "HARVEST": "Crop gathering",
    "HEADSET": "Call centre gear",
    "HEALTHY": "In good shape",
    "HEARING": "Sense of sound",
    "HEATHER": "Moor plant",
    "HEAVILY": "With force",
    "HEDGEHOG": "Spiny forager",
    "HEIGHTS": "High places",
    "HELPFUL": "Kind and useful",
    "HIGHWAY": "Main road",
    "HISTORY": "Past events",
    "HOLIDAY": "Vacation",
    "HORIZON": "Where sky meets land",
    "HORMONE": "Body chemical",
    "HOSTAGE": "Captive",
    "HOSTESS": "Party greeter",
    "HOUSING": "Places to live",
    "HOWEVER": "Nevertheless",
    "HUNDRED": "Ten tens",
    "HUNTING": "The chase",
    "HUSBAND": "Spouse",
    "HYGIENE": "Cleanliness",
    "ILLNESS": "Sickness",
    "IMAGINE": "Picture it",
    "IMMENSE": "Huge",
    "IMPLANT": "Surgical insert",
    "IMPRESS": "Wow someone",
    "IMPROVE": "Make better",
    "IMPULSE": "Sudden urge",
    "INCENSE": "Fragrant smoke",
    "INCLINE": "Slope",
    "INCLUDE": "Contain",
    "INDOORS": "Inside the house",
    "INFERNO": "Raging fire",
    "INFLATE": "Blow up",
    "INKWELL": "Old pen pot",
    "INNINGS": "Baseball division",
    "INQUIRE": "Ask",
    "INSIGHT": "Deep understanding",
    "INSPECT": "Examine",
    "INSTALL": "Set up",
    "INSTANT": "Immediate",
    "INSTEAD": "Rather",
    "INTEGER": "Whole number",
    "INTENSE": "Very strong",
    "INTERIM": "Temporary",
    "INTRUDE": "Barge in",
    "INVADER": "Intruder",
    "INVOICE": "Bill",
    "JACKETS": "Blazers, plural",
    "JASMINE": "Fragrant flower",
    "JAVELIN": "Throwing spear",
    "JEALOUS": "Green-eyed",
    "JEWELRY": "Rings and things",
    "JOURNAL": "Diary",
    "JOURNEY": "Long trip",
    "JUBILEE": "Celebration",
    "JUSTICE": "Fairness",
    "JUSTIFY": "Give reason for",
    "KETCHUP": "Tomato sauce",
    "KEYHOLE": "Lock opening",
    "KINDRED": "Similar in spirit",
    "KINGDOM": "Realm",
    "KINSHIP": "Family tie",
    "KITCHEN": "Where you cook",
    "KNOWING": "Aware",
    "LANTERN": "Portable light",
    "LATTICE": "Criss-cross frame",
    "LAUNDRY": "Wash day pile",
    "LEADING": "In front",
    "LEATHER": "Hide material",
    "LECTURE": "Long talk",
    "LIBERTY": "Freedom",
    "LIBRARY": "Book lender",
    "LICENSE": "Official permit",
    "LOGICAL": "Sensible",
    "LONGING": "Deep want",
    "LOTTERY": "Number game",
    "LOVABLE": "Easy to adore",
    "LOWLAND": "Flat country",
    "LOYALTY": "Faithfulness",
    "LUGGAGE": "Bags",
    "LULLABY": "Sleep song",
    "MACHINE": "Engine-driven device",
    "MAJESTY": "Royal grandeur",
    "MANKIND": "All humans",
    "MANSION": "Big house",
    "MARINER": "Sailor",
    "MARTIAN": "Of Mars",
    "MASCARA": "Lash makeup",
    "MASSAGE": "Rub down",
    "MASSIVE": "Very big",
    "MATADOR": "Bullfighter",
    "MAXIMUM": "Most possible",
    "MEANING": "Sense",
    "MEASURE": "Size it up",
    "MEDICAL": "Health-related",
    "MEETING": "Gathering",
    "MENTION": "Bring up",
    "MERMAID": "Sea maiden",
    "MESSAGE": "Note sent",
    "MICROBE": "Germ",
    "MIGRATE": "Move with the season",
    "MINERAL": "Rock nutrient",
    "MINIMUM": "Least possible",
    "MIRACLE": "Wonder",
    "MISSILE": "Guided weapon",
    "MISSION": "Task",
    "MISTAKE": "Error",
    "MIXTURE": "Blend",
    "MOCKING": "Taunting",
    "MONITOR": "Watch closely",
    "MONSTER": "Frightful beast",
    "MONTHLY": "Every month",
    "MORNING": "Day's start",
    "MOVABLE": "Not fixed",
    "MUNDANE": "Dull and ordinary",
    "MUSTARD": "Yellow condiment",
    "MYSTERY": "Unsolved puzzle",
    "MYSTIFY": "Puzzle someone",
    "NATURAL": "Not artificial",
    "NEGLECT": "Ignore",
    "NERVOUS": "Jittery",
    "NETWORK": "Linked system",
    "NEUTRON": "Chargeless particle",
    "NIGHTLY": "Every night",
    "NOMINAL": "In name only",
    "NOSTRIL": "Nose opening",
    "NOTABLE": "Worth mentioning",
    "NOTHING": "Zilch",
    "NOURISH": "Feed well",
    "NOVELTY": "Newness, or a gimmick",
    "NUCLEAR": "Of the atom",
    "NURSERY": "Baby's room",
    "NURTURE": "Care for",
    "OATMEAL": "Breakfast mush",
    "OBSERVE": "Watch",
    "OBVIOUS": "Plain to see",
    "OCTOPUS": "Eight-armed one",
    "ODYSSEY": "Long adventure",
    "OFFENSE": "Crime, or an attack",
    "OFFICER": "Badge holder",
    "OFFICIAL": "Formal",
    "OPENING": "First night, or a gap",
    "OPERATE": "Run, or do surgery",
    "OPINION": "Point of view",
    "OPTICAL": "Of the eye",
    "ORCHARD": "Fruit farm",
    "ORIGAMI": "Paper folding",
    "OSMOSIS": "Slow soak-through",
    "OTTOMAN": "Footstool",
    "OUTCOME": "End result",
    "OUTDOOR": "Open air",
    "OUTINGS": "Little trips",
    "OUTLINE": "Sketch of a plan",
    "OUTPOST": "Remote base",
    "OUTSIDE": "Not in here",
    "OVERALL": "In general",
    "OVERLAP": "Partly cover",
    "PACKAGE": "Box delivered",
    "PADLOCK": "Hanging lock",
    "PAGEANT": "Beauty contest",
    "PAINFUL": "Sore",
    "PALETTE": "Painter's board",
    "PANCAKE": "Griddle item",
    "PANICKY": "Freaking out",
    "PANTHER": "Sleek big cat",
    "PARADES": "Floats and bands",
    "PARAGON": "Perfect model",
    "PARASOL": "Sun umbrella",
    "PARKING": "Car placement",
    "PARTIAL": "Not complete",
    "PARTNER": "Mate",
    "PASSAGE": "Way through",
    "PASSION": "Strong feeling",
    "PASSIVE": "Not active",
    "PASTURE": "Grazing field",
    "PATIENT": "Waiting calmly",
    "PATTERN": "Repeated design",
    "PEACOCK": "Fancy-tail bird",
    "PEASANT": "Farm worker of old",
    "PELICAN": "Big-billed fisher",
    "PENALTY": "Punishment",
    "PENGUIN": "Tuxedo bird",
    "PENNANT": "Champion flag",
    "PENSION": "Retirement pay",
    "PERCENT": "Per hundred",
    "PERFECT": "Flawless",
    "PERFUME": "Scent",
    "PERHAPS": "Maybe",
    "PERSIST": "Keep at it",
    "PHANTOM": "Ghostly figure",
    "PHARAOH": "Egyptian ruler",
    "PHONICS": "Sound-based reading",
    "PHYSICS": "Science of forces",
    "PICTURE": "Image",
    "PIGMENT": "Colour source",
    "PILGRIM": "Journeying believer",
    "PIONEER": "Trailblazer",
    "PITCHER": "Jug",
    "PIVOTAL": "Crucial",
    "PLASTER": "Wall coat",
    "PLASTIC": "Synthetic material",
    "PLATEAU": "Flat highland",
    "PLATTER": "Serving tray",
    "PLUMBER": "Pipe fixer",
    "POACHER": "Illegal hunter",
    "POINTER": "Hint",
    "POPCORN": "Movie snack",
    "POPULAR": "Well liked",
    "PORTION": "Share",
    "POSTAGE": "Mail cost",
    "POTTERY": "Clay craft",
    "POULTRY": "Chicken meat",
    "POVERTY": "Being poor",
    "PRAIRIE": "Grassland",
    "PRECISE": "Exact",
    "PREDICT": "Foretell",
    "PREFACE": "Book intro",
    "PREMIER": "Top, or a leader",
    "PREMIUM": "Top quality",
    "PREPARE": "Get ready",
    "PRESENT": "Here, or a gift",
    "PREVAIL": "Win out",
    "PREVENT": "Stop it happening",
    "PRICKLY": "Spiky",
    "PRIMARY": "First",
    "PRINTER": "Paper output device",
    "PRIVATE": "Not public",
    "PROCEED": "Go ahead",
    "PROCESS": "Series of steps",
    "PRODUCE": "Bring forth, or veggies",
    "PROFESS": "Claim",
    "PROFILE": "Face seen from the side",
    "PROGRAM": "Software",
    "PROJECT": "Big task",
    "PROMISE": "Vow",
    "PROMOTE": "Push upward",
    "PROPOSE": "Ask the question",
    "PROSPER": "Do well",
    "PROTECT": "Guard",
    "PROTEIN": "Muscle nutrient",
    "PROTEST": "Object loudly",
    "PROUDLY": "With pride",
    "PROVIDE": "Supply",
    "PROVOKE": "Goad",
    "PROWESS": "Great skill",
    "PRUDENT": "Wise and careful",
    "PUDDING": "Dessert",
    "PURPOSE": "Reason for being",
    "PURSUIT": "The chase",
    "PYRAMID": "Egyptian tomb",
    "QUALIFY": "Meet the bar",
    "QUARREL": "Squabble",
    "QUARTER": "Twenty-five cents",
    "QUEENLY": "Fit for royalty",
    "QUICKLY": "At speed",
    "QUIETLY": "Without noise",
    "QUINTET": "Group of five",
    "RACCOON": "Masked trash raider",
    "RACQUET": "Tennis gear",
    "RADIANT": "Glowing",
    "RADICAL": "Extreme",
    "RAMPART": "Defensive wall",
    "RANCHER": "Cattle farmer",
    "RAPIDLY": "Very fast",
    "REACHED": "Got to",
    "READILY": "Without fuss",
    "REALITY": "Actual life",
    "RECEIPT": "Proof of purchase",
    "RECITAL": "Music performance",
    "RECLAIM": "Get back",
    "RECOVER": "Get well",
    "RECRUIT": "New hire",
    "REFEREE": "Whistle blower",
    "REFLECT": "Mirror back, or ponder",
    "REFUGEE": "Displaced person",
    "REFUSAL": "A no",
    "REGATTA": "Boat race",
    "REGIMEN": "Routine",
    "REGULAR": "Normal",
    "REJOICE": "Celebrate",
    "RELAPSE": "Slip back",
    "RELEASE": "Let go",
    "RELIEVE": "Ease",
    "REMOVAL": "Taking away",
    "RENEWAL": "Fresh start",
    "REPLACE": "Swap out",
    "REPLICA": "Copy",
    "REPTILE": "Scaly creature",
    "REQUEST": "Ask for",
    "RESERVE": "Book ahead",
    "RESIDUE": "What's left over",
    "RESOLVE": "Settle it",
    "RESPECT": "Look up to",
    "RESPOND": "Answer",
    "RESTORE": "Bring back",
    "RETREAT": "Fall back",
    "REUNION": "Family get-together",
    "REVENGE": "Payback",
    "REVERSE": "Go backwards",
    "RHUBARB": "Tart red stalk",
    "RIOTOUS": "Wild and loud",
    "ROADWAY": "Street surface",
    "ROBBERY": "Theft",
    "ROMANCE": "Love affair",
    "ROOFTOP": "Top of a building",
    "ROSEBUD": "Tightly closed flower",
    "ROYALTY": "Kings and queens",
    "RUBBISH": "Trash, or nonsense",
    "RUNAWAY": "Out of control",
    "SAMURAI": "Japanese warrior",
    "SANDBOX": "Playground box",
    "SATCHEL": "Shoulder bag",
    "SATISFY": "Fill the need",
    "SAUSAGE": "Cased meat",
    "SCANNER": "Bar-code reader",
    "SCATTER": "Spread out",
    "SCENERY": "Views",
    "SCHOLAR": "Learned one",
    "SCIENCE": "Lab work",
    "SCOOTER": "Kick scooter",
    "SCRAPER": "Ice remover",
    "SEAGULL": "Beach thief",
    "SEAPORT": "Coastal city",
    "SEASIDE": "The shore",
    "SECRECY": "Keeping it quiet",
    "SECTION": "Part",
    "SEGMENT": "Slice",
    "SEIZURE": "Sudden take",
    "SENATOR": "Capitol figure",
    "SENSORY": "Of the senses",
    "SEQUOIA": "Giant tree",
    "SERPENT": "Snake",
    "SERVICE": "Help given",
    "SERVING": "Portion of food",
    "SESSION": "Sitting",
    "SETBACK": "Delay",
    "SETTING": "Background",
    "SEVENTH": "Ordinal number",
    "SEVERAL": "A few",
    "SHALLOW": "Not deep",
    "SHAMPOO": "Hair wash",
    "SHARPEN": "Put an edge on",
    "SHELTER": "Cover",
    "SHERIFF": "County lawman",
    "SHIMMER": "Soft shine",
    "SINGING": "Using your voice",
    "SHINGLE": "Roof tile",
    "SHOEBOX": "Small cardboard box",
    "SHORTLY": "Soon",
    "SHOWMAN": "Performer type",
    "SHUFFLE": "Mix cards",
    "SHUTTER": "Window cover",
    "SHUTTLE": "Frequent flier",
    "SIBLING": "Brother or sister",
    "SILENCE": "Quiet",
    "SILICON": "Chip material",
    "SIMILAR": "Alike",
    "SINCERE": "Heartfelt",
    "SIXTEEN": "Four fours",
    "SKEPTIC": "Doubter",
    "SKETCHY": "Dodgy",
    "SKILLET": "Frying pan",
    "SKYLINE": "City silhouette",
    "SLEEPER": "Pyjamas, or a sleeper hit",
    "SLENDER": "Slim",
    "SLIPPER": "House shoe",
    "SLUMBER": "Sleep",
    "SMUGGLE": "Sneak in goods",
    "SNEAKER": "Athletic shoe",
    "SNORKEL": "Diving tube",
    "SNOWMAN": "Carrot-nosed fellow",
    "SOLDIER": "Army member",
    "SOLICIT": "Ask for",
    "SOMEHOW": "By some means",
    "SOMEONE": "A person",
    "SOPRANO": "High singer",
    "SORCERY": "Wizardry",
    "SOULFUL": "Deeply felt",
    "SPARKLE": "Twinkle",
    "SPARROW": "Little brown bird",
    "SPEAKER": "Podium user",
    "SPECIAL": "One of a kind",
    "SPECIES": "Biological group",
    "SPECTER": "Ghost",
    "SPINACH": "Leafy green",
    "SPIRITS": "Alcohol, or moods",
    "SPLASHY": "Showy",
    "SPOILED": "Gone bad, or doted on",
    "SPONSOR": "Backer",
    "SPRINGS": "Coils",
    "SQUARES": "Plaza bits",
    "SQUIRREL": "Nut hoarder",
    "STADIUM": "Big arena",
    "STAMINA": "Endurance",
    "STANDBY": "Backup",
    "STARTER": "First course",
    "STARTLE": "Surprise",
    "STATION": "Train stop",
    "STEALTH": "Sneaky approach",
    "STEAMER": "Clam, or a ship",
    "STEEPLE": "Church tower",
    "STELLAR": "Outstanding",
    "STENCIL": "Cut-out template",
    "STEREO": "Sound equipment",
    "STERNUM": "Breastbone",
    "STICKER": "Decal",
    "STIMULI": "Inputs",
    "STOMACH": "Food organ",
    "STORAGE": "Space to keep things",
    "STRANGE": "Odd",
    "STRETCH": "Extend, or a warm-up",
    "STUBBLE": "Short beard",
    "STUDENT": "Learner",
    "STUMBLE": "Trip",
    "STYLISH": "Trendy",
    "SUBJECT": "Topic",
    "SUBLIME": "Exalted",
    "SUBTLE": "Understated",
    "SUCCEED": "Do well",
    "SUCCESS": "A win",
    "SUDDEN": "Abrupt",
    "SUGGEST": "Propose",
    "SUMMARY": "Recap",
    "SUMMONS": "Official call",
    "SUNBEAM": "Ray of light",
    "SUNBURN": "Beach regret",
    "SUNRISE": "Dawn",
    "SUPREME": "Highest",
    "SURFACE": "Top layer",
    "SURGEON": "Operating doctor",
    "SURNAME": "Family name",
    "SURPLUS": "Extra amount",
    "SURREAL": "Dreamlike",
    "SURVIVE": "Make it through",
    "SUSPECT": "Think likely",
    "SUSPEND": "Hang, or pause",
    "SUSTAIN": "Keep going",
    "SWALLOW": "Bird, or to gulp",
    "SWEATER": "Knit top",
    "SWEETEN": "Add sugar",
    "SWEETLY": "In a kind way",
    "SWIMMER": "Pool user",
    "SWINDLE": "Cheat",
    "SYRINGE": "Needle for shots",
    "TACTICS": "Strategy",
    "TAFFETA": "Crisp fabric",
    "TAILOR": "Suit maker",
    "TANKARD": "Beer mug",
    "TANTRUM": "Fling",
    "TAPIOCA": "Pudding type",
    "TARGETS": "Goals",
    "TARIFFS": "Import taxes",
    "TASTING": "Sampling",
    "TEACHER": "Instructor",
    "TEAPOT": "Brew vessel",
    "TEASING": "Ribbing",
    "TEMPEST": "Violent storm",
    "TENFOLD": "Times ten",
    "TENSION": "Strain",
    "TERMITE": "Wood eater",
    "TERRAIN": "Landscape",
    "TERRACE": "Patio",
    "TERRIFY": "Scare badly",
    "TESTIFY": "Give evidence",
    "TEXTILE": "Woven fabric",
    "TEXTURE": "Feel of a surface",
    "THEATER": "Playhouse",
    "THERAPY": "Talking cure",
    "THICKET": "Dense brush",
    "THIMBLE": "Sewing cap",
    "THINKER": "Ponderer",
    "THIRSTY": "Needing a drink",
    "THISTLE": "Prickly plant",
    "THOUGHT": "Idea",
    "THRIFTY": "Careful with cash",
    "THUNDER": "Sky rumble",
    "TIDINGS": "News",
    "TIGHTEN": "Make snug",
    "TIPTOE": "Walk quietly",
    "TOASTER": "Bread browner",
    "TOBACCO": "Pipe filler",
    "TONIGHT": "This evening",
    "TOOLBOX": "Handyman's kit",
    "TOPICAL": "Current",
    "TORNADO": "Twister",
    "TORRENT": "Downpour",
    "TOURISM": "Travel trade",
    "TOURIST": "Sightseer",
    "TRACTOR": "Farm hauler",
    "TRAFFIC": "Road jam",
    "TRAGEDY": "Disaster",
    "TRAILER": "Towed home",
    "TRAITOR": "Betrayer",
    "TRAMPLE": "Walk over",
    "TRANSIT": "Public transport",
    "TRAPEZE": "Circus swing",
    "TREASON": "Betraying a nation",
    "TRIBUTE": "Tribute",
    "TRICKLE": "Small flow",
    "TRIGGER": "Gun lever",
    "TRINKET": "Small bauble",
    "TRIPLET": "One of three",
    "TRIUMPH": "Great win",
    "TRIVIAL": "Small fry",
    "TROLLEY": "Streetcar",
    "TROOPER": "State cop",
    "TROPICS": "Warm latitudes",
    "TROUBLE": "Bother",
    "TRUCKER": "Hauler driver",
    "TRUMPET": "Brass horn",
    "TSUNAMI": "Big wave",
    "TUESDAY": "Day after Monday",
    "TUITION": "School fees",
    "TUMBLER": "Glass",
    "TURBINE": "Power spinner",
    "TURMOIL": "Great confusion",
    "TURNOUT": "Attendance",
    "TWINKLE": "Star sparkle",
    "TWISTER": "Tornado",
    "TYPICAL": "Usual",
    "TYRANNY": "Cruel rule",
    "UNAWARE": "Not knowing",
    "UNCLEAR": "Confusing",
    "UNCOVER": "Reveal",
    "UNDERGO": "Go through",
    "UNDOING": "Ruin",
    "UNEARTH": "Dig up",
    "UNHAPPY": "Sad",
    "UNICORN": "Horned horse",
    "UNIFORM": "Team outfit",
    "UNKEMPT": "Messy",
    "UNLUCKY": "Snakebit",
    "UPGRADE": "Better version",
    "VALIANT": "Brave",
    "VAMPIRE": "Bat tyrant",
    "VANILLA": "Plain flavour",
    "VARIETY": "Assortment",
    "VARIOUS": "Many kinds",
    "VARNISH": "Wood coating",
    "VEHICLE": "Car or truck",
    "VENDING": "Machine selling",
    "VENTURE": "Risky project",
    "VERANDA": "Covered porch",
    "VERDICT": "Jury's call",
    "VERSION": "Variant",
    "VETERAN": "Old hand",
    "VIBRANT": "Full of life",
    "VICTORY": "A win",
    "VILLAGE": "Small town",
    "VILLAIN": "Bad guy",
    "VINEGAR": "Sour liquid",
    "VINTAGE": "Old and classy",
    "VIRTUAL": "Computer-simulated",
    "VISIBLE": "Can be seen",
    "VISITOR": "Guest",
    "VITAMIN": "Nutrition pill",
    "VOLCANO": "Mountain with lava",
    "VOLTAGE": "Electrical push",
    "VOUCHER": "Coupon",
    "VOYAGER": "Long-distance traveler",
    "WARLOCK": "Male witch",
    "WARRANT": "Search order",
    "WARRIOR": "Fighter",
    "WATCHER": "Observer",
    "WEATHER": "Rain or shine",
    "WEDDING": "Big day with cake",
    "WEEKEND": "Saturday and Sunday",
    "WELCOME": "Greeting mat word",
    "WELFARE": "Well-being",
    "WHETHER": "If",
    "WHISPER": "Quiet word",
    "WHISTLE": "Referee's sound",
    "WHOEVER": "Any person who",
    "WIDOWER": "Man who lost a spouse",
    "WILLING": "Ready to go",
    "WITNESS": "One who saw it",
    "WOMANLY": "Feminine",
    "WORKOUT": "Gym session",
    "WORSHIP": "Adoration",
    "WRESTLE": "Grapple",
    "WRINKLE": "Face fold",
    "WRITING": "Scribbling",
    "WRITTEN": "Put down on paper",
    "YOUNGER": "Less old",
    "ZEALOUS": "Fervent",

    # ---- 8 letters ----
    "ABSOLUTE": "Total and complete",
    "ACTIVITY": "Something you do",
    "AIRPLANE": "Winged flier",
    "ANCESTOR": "Forebear",
    "AUDIENCE": "Crowd watching",
    "AVALANCHE": "Roaring snow slide",
    "BALLOONS": "Party floaters",
    "BIRTHDAY": "Cake day",
    "BLIZZARD": "Snow storm",
    "CALENDAR": "Date planner",
    "CHOCOLATE": "Cocoa treat",
    "CINNAMON": "Spice roll flavour",
    "COMPUTER": "Desktop or laptop",
    "DINOSAUR": "Ancient giant",
    "ELEPHANT": "Trunk owner",
    "ELEVATOR": "Rising box",
    "FIREWORK": "Sky sparkler",
    "FOOTBALL": "Sunday sport",
    "HOSPITAL": "Where doctors work",
    "KEYBOARD": "Ivory row, or a typing tool",
    "LIGHTNING": "Sky flash",
    "MAGAZINE": "Glossy monthly",
    "MEMORIES": "Things recalled",
    "MISTAKEN": "In error",
    "MOUNTAIN": "Tall peak",
    "NOTEBOOK": "Where you scribble",
    "OBSTACLE": "Hindrance",
    "OUTSIDER": "One not in the group",
    "PASSWORD": "Login secret",
    "PINEAPPLE": "Spiky fruit",
    "POPULATION": "Head count",
    "SANDWICH": "Meal between bread",
    "SENTENCE": "String of words",
    "SNAPSHOT": "Quick photo",
    "STRAWBERRY": "Seedy berry",
    "SUNSHINE": "Bright light",
    "SURPRISE": "Something unexpected",
    "TELEGRAM": "Old-style wire message",
    "TREASURE": "Buried riches",
    "UMBRELLA": "Rain cover",
    "VACATION": "Time off",
    "WILDFIRE": "Out-of-control blaze",
    "YARDWORK": "Mowing and raking",
}
